package com.ut.scf.pojo.auto;

import java.util.Date;

public class SysUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.user_id
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.username
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.password
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.realname
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	private String realname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.email
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.mobilephone
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	private String mobilephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.fixed_phone
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	private String fixedPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.corp_id
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	private String corpId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.dept_id
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	private String deptId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.photo_url
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	private String photoUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.note
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	private String note;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.create_time
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.status
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	private Byte status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.user_id
	 * @return  the value of sys_user.user_id
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.user_id
	 * @param userId  the value for sys_user.user_id
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.username
	 * @return  the value of sys_user.username
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.username
	 * @param username  the value for sys_user.username
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.password
	 * @return  the value of sys_user.password
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.password
	 * @param password  the value for sys_user.password
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.realname
	 * @return  the value of sys_user.realname
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	public String getRealname() {
		return realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.realname
	 * @param realname  the value for sys_user.realname
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	public void setRealname(String realname) {
		this.realname = realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.email
	 * @return  the value of sys_user.email
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.email
	 * @param email  the value for sys_user.email
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.mobilephone
	 * @return  the value of sys_user.mobilephone
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	public String getMobilephone() {
		return mobilephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.mobilephone
	 * @param mobilephone  the value for sys_user.mobilephone
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	public void setMobilephone(String mobilephone) {
		this.mobilephone = mobilephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.fixed_phone
	 * @return  the value of sys_user.fixed_phone
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	public String getFixedPhone() {
		return fixedPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.fixed_phone
	 * @param fixedPhone  the value for sys_user.fixed_phone
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	public void setFixedPhone(String fixedPhone) {
		this.fixedPhone = fixedPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.corp_id
	 * @return  the value of sys_user.corp_id
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	public String getCorpId() {
		return corpId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.corp_id
	 * @param corpId  the value for sys_user.corp_id
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	public void setCorpId(String corpId) {
		this.corpId = corpId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.dept_id
	 * @return  the value of sys_user.dept_id
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	public String getDeptId() {
		return deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.dept_id
	 * @param deptId  the value for sys_user.dept_id
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.photo_url
	 * @return  the value of sys_user.photo_url
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	public String getPhotoUrl() {
		return photoUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.photo_url
	 * @param photoUrl  the value for sys_user.photo_url
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	public void setPhotoUrl(String photoUrl) {
		this.photoUrl = photoUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.note
	 * @return  the value of sys_user.note
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.note
	 * @param note  the value for sys_user.note
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.create_time
	 * @return  the value of sys_user.create_time
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.create_time
	 * @param createTime  the value for sys_user.create_time
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.status
	 * @return  the value of sys_user.status
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.status
	 * @param status  the value for sys_user.status
	 * @mbggenerated  Wed May 31 14:45:01 CST 2017
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}
}