package com.ut.scf.pojo.auto;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Iterator;

public class CarInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	public CarInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andCarFrameNumIsNull() {
			addCriterion("car_frame_num is null");
			return (Criteria) this;
		}

		public Criteria andCarFrameNumIsNotNull() {
			addCriterion("car_frame_num is not null");
			return (Criteria) this;
		}

		public Criteria andCarFrameNumEqualTo(String value) {
			addCriterion("car_frame_num =", value, "carFrameNum");
			return (Criteria) this;
		}

		public Criteria andCarFrameNumNotEqualTo(String value) {
			addCriterion("car_frame_num <>", value, "carFrameNum");
			return (Criteria) this;
		}

		public Criteria andCarFrameNumGreaterThan(String value) {
			addCriterion("car_frame_num >", value, "carFrameNum");
			return (Criteria) this;
		}

		public Criteria andCarFrameNumGreaterThanOrEqualTo(String value) {
			addCriterion("car_frame_num >=", value, "carFrameNum");
			return (Criteria) this;
		}

		public Criteria andCarFrameNumLessThan(String value) {
			addCriterion("car_frame_num <", value, "carFrameNum");
			return (Criteria) this;
		}

		public Criteria andCarFrameNumLessThanOrEqualTo(String value) {
			addCriterion("car_frame_num <=", value, "carFrameNum");
			return (Criteria) this;
		}

		public Criteria andCarFrameNumLike(String value) {
			addCriterion("car_frame_num like", value, "carFrameNum");
			return (Criteria) this;
		}

		public Criteria andCarFrameNumNotLike(String value) {
			addCriterion("car_frame_num not like", value, "carFrameNum");
			return (Criteria) this;
		}

		public Criteria andCarFrameNumIn(List<String> values) {
			addCriterion("car_frame_num in", values, "carFrameNum");
			return (Criteria) this;
		}

		public Criteria andCarFrameNumNotIn(List<String> values) {
			addCriterion("car_frame_num not in", values, "carFrameNum");
			return (Criteria) this;
		}

		public Criteria andCarFrameNumBetween(String value1, String value2) {
			addCriterion("car_frame_num between", value1, value2, "carFrameNum");
			return (Criteria) this;
		}

		public Criteria andCarFrameNumNotBetween(String value1, String value2) {
			addCriterion("car_frame_num not between", value1, value2,
					"carFrameNum");
			return (Criteria) this;
		}

		public Criteria andCarNoIsNull() {
			addCriterion("car_no is null");
			return (Criteria) this;
		}

		public Criteria andCarNoIsNotNull() {
			addCriterion("car_no is not null");
			return (Criteria) this;
		}

		public Criteria andCarNoEqualTo(String value) {
			addCriterion("car_no =", value, "carNo");
			return (Criteria) this;
		}

		public Criteria andCarNoNotEqualTo(String value) {
			addCriterion("car_no <>", value, "carNo");
			return (Criteria) this;
		}

		public Criteria andCarNoGreaterThan(String value) {
			addCriterion("car_no >", value, "carNo");
			return (Criteria) this;
		}

		public Criteria andCarNoGreaterThanOrEqualTo(String value) {
			addCriterion("car_no >=", value, "carNo");
			return (Criteria) this;
		}

		public Criteria andCarNoLessThan(String value) {
			addCriterion("car_no <", value, "carNo");
			return (Criteria) this;
		}

		public Criteria andCarNoLessThanOrEqualTo(String value) {
			addCriterion("car_no <=", value, "carNo");
			return (Criteria) this;
		}

		public Criteria andCarNoLike(String value) {
			addCriterion("car_no like", value, "carNo");
			return (Criteria) this;
		}

		public Criteria andCarNoNotLike(String value) {
			addCriterion("car_no not like", value, "carNo");
			return (Criteria) this;
		}

		public Criteria andCarNoIn(List<String> values) {
			addCriterion("car_no in", values, "carNo");
			return (Criteria) this;
		}

		public Criteria andCarNoNotIn(List<String> values) {
			addCriterion("car_no not in", values, "carNo");
			return (Criteria) this;
		}

		public Criteria andCarNoBetween(String value1, String value2) {
			addCriterion("car_no between", value1, value2, "carNo");
			return (Criteria) this;
		}

		public Criteria andCarNoNotBetween(String value1, String value2) {
			addCriterion("car_no not between", value1, value2, "carNo");
			return (Criteria) this;
		}

		public Criteria andFinanceIdIsNull() {
			addCriterion("finance_id is null");
			return (Criteria) this;
		}

		public Criteria andFinanceIdIsNotNull() {
			addCriterion("finance_id is not null");
			return (Criteria) this;
		}

		public Criteria andFinanceIdEqualTo(String value) {
			addCriterion("finance_id =", value, "financeId");
			return (Criteria) this;
		}

		public Criteria andFinanceIdNotEqualTo(String value) {
			addCriterion("finance_id <>", value, "financeId");
			return (Criteria) this;
		}

		public Criteria andFinanceIdGreaterThan(String value) {
			addCriterion("finance_id >", value, "financeId");
			return (Criteria) this;
		}

		public Criteria andFinanceIdGreaterThanOrEqualTo(String value) {
			addCriterion("finance_id >=", value, "financeId");
			return (Criteria) this;
		}

		public Criteria andFinanceIdLessThan(String value) {
			addCriterion("finance_id <", value, "financeId");
			return (Criteria) this;
		}

		public Criteria andFinanceIdLessThanOrEqualTo(String value) {
			addCriterion("finance_id <=", value, "financeId");
			return (Criteria) this;
		}

		public Criteria andFinanceIdLike(String value) {
			addCriterion("finance_id like", value, "financeId");
			return (Criteria) this;
		}

		public Criteria andFinanceIdNotLike(String value) {
			addCriterion("finance_id not like", value, "financeId");
			return (Criteria) this;
		}

		public Criteria andFinanceIdIn(List<String> values) {
			addCriterion("finance_id in", values, "financeId");
			return (Criteria) this;
		}

		public Criteria andFinanceIdNotIn(List<String> values) {
			addCriterion("finance_id not in", values, "financeId");
			return (Criteria) this;
		}

		public Criteria andFinanceIdBetween(String value1, String value2) {
			addCriterion("finance_id between", value1, value2, "financeId");
			return (Criteria) this;
		}

		public Criteria andFinanceIdNotBetween(String value1, String value2) {
			addCriterion("finance_id not between", value1, value2, "financeId");
			return (Criteria) this;
		}

		public Criteria andStoreNameIsNull() {
			addCriterion("store_name is null");
			return (Criteria) this;
		}

		public Criteria andStoreNameIsNotNull() {
			addCriterion("store_name is not null");
			return (Criteria) this;
		}

		public Criteria andStoreNameEqualTo(String value) {
			addCriterion("store_name =", value, "storeName");
			return (Criteria) this;
		}

		public Criteria andStoreNameNotEqualTo(String value) {
			addCriterion("store_name <>", value, "storeName");
			return (Criteria) this;
		}

		public Criteria andStoreNameGreaterThan(String value) {
			addCriterion("store_name >", value, "storeName");
			return (Criteria) this;
		}

		public Criteria andStoreNameGreaterThanOrEqualTo(String value) {
			addCriterion("store_name >=", value, "storeName");
			return (Criteria) this;
		}

		public Criteria andStoreNameLessThan(String value) {
			addCriterion("store_name <", value, "storeName");
			return (Criteria) this;
		}

		public Criteria andStoreNameLessThanOrEqualTo(String value) {
			addCriterion("store_name <=", value, "storeName");
			return (Criteria) this;
		}

		public Criteria andStoreNameLike(String value) {
			addCriterion("store_name like", value, "storeName");
			return (Criteria) this;
		}

		public Criteria andStoreNameNotLike(String value) {
			addCriterion("store_name not like", value, "storeName");
			return (Criteria) this;
		}

		public Criteria andStoreNameIn(List<String> values) {
			addCriterion("store_name in", values, "storeName");
			return (Criteria) this;
		}

		public Criteria andStoreNameNotIn(List<String> values) {
			addCriterion("store_name not in", values, "storeName");
			return (Criteria) this;
		}

		public Criteria andStoreNameBetween(String value1, String value2) {
			addCriterion("store_name between", value1, value2, "storeName");
			return (Criteria) this;
		}

		public Criteria andStoreNameNotBetween(String value1, String value2) {
			addCriterion("store_name not between", value1, value2, "storeName");
			return (Criteria) this;
		}

		public Criteria andPayDateIsNull() {
			addCriterion("pay_date is null");
			return (Criteria) this;
		}

		public Criteria andPayDateIsNotNull() {
			addCriterion("pay_date is not null");
			return (Criteria) this;
		}

		public Criteria andPayDateEqualTo(Date value) {
			addCriterionForJDBCDate("pay_date =", value, "payDate");
			return (Criteria) this;
		}

		public Criteria andPayDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("pay_date <>", value, "payDate");
			return (Criteria) this;
		}

		public Criteria andPayDateGreaterThan(Date value) {
			addCriterionForJDBCDate("pay_date >", value, "payDate");
			return (Criteria) this;
		}

		public Criteria andPayDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("pay_date >=", value, "payDate");
			return (Criteria) this;
		}

		public Criteria andPayDateLessThan(Date value) {
			addCriterionForJDBCDate("pay_date <", value, "payDate");
			return (Criteria) this;
		}

		public Criteria andPayDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("pay_date <=", value, "payDate");
			return (Criteria) this;
		}

		public Criteria andPayDateIn(List<Date> values) {
			addCriterionForJDBCDate("pay_date in", values, "payDate");
			return (Criteria) this;
		}

		public Criteria andPayDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("pay_date not in", values, "payDate");
			return (Criteria) this;
		}

		public Criteria andPayDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("pay_date between", value1, value2,
					"payDate");
			return (Criteria) this;
		}

		public Criteria andPayDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("pay_date not between", value1, value2,
					"payDate");
			return (Criteria) this;
		}

		public Criteria andCarActualPriceIsNull() {
			addCriterion("car_actual_price is null");
			return (Criteria) this;
		}

		public Criteria andCarActualPriceIsNotNull() {
			addCriterion("car_actual_price is not null");
			return (Criteria) this;
		}

		public Criteria andCarActualPriceEqualTo(BigDecimal value) {
			addCriterion("car_actual_price =", value, "carActualPrice");
			return (Criteria) this;
		}

		public Criteria andCarActualPriceNotEqualTo(BigDecimal value) {
			addCriterion("car_actual_price <>", value, "carActualPrice");
			return (Criteria) this;
		}

		public Criteria andCarActualPriceGreaterThan(BigDecimal value) {
			addCriterion("car_actual_price >", value, "carActualPrice");
			return (Criteria) this;
		}

		public Criteria andCarActualPriceGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("car_actual_price >=", value, "carActualPrice");
			return (Criteria) this;
		}

		public Criteria andCarActualPriceLessThan(BigDecimal value) {
			addCriterion("car_actual_price <", value, "carActualPrice");
			return (Criteria) this;
		}

		public Criteria andCarActualPriceLessThanOrEqualTo(BigDecimal value) {
			addCriterion("car_actual_price <=", value, "carActualPrice");
			return (Criteria) this;
		}

		public Criteria andCarActualPriceIn(List<BigDecimal> values) {
			addCriterion("car_actual_price in", values, "carActualPrice");
			return (Criteria) this;
		}

		public Criteria andCarActualPriceNotIn(List<BigDecimal> values) {
			addCriterion("car_actual_price not in", values, "carActualPrice");
			return (Criteria) this;
		}

		public Criteria andCarActualPriceBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("car_actual_price between", value1, value2,
					"carActualPrice");
			return (Criteria) this;
		}

		public Criteria andCarActualPriceNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("car_actual_price not between", value1, value2,
					"carActualPrice");
			return (Criteria) this;
		}

		public Criteria andCarColorIsNull() {
			addCriterion("car_color is null");
			return (Criteria) this;
		}

		public Criteria andCarColorIsNotNull() {
			addCriterion("car_color is not null");
			return (Criteria) this;
		}

		public Criteria andCarColorEqualTo(String value) {
			addCriterion("car_color =", value, "carColor");
			return (Criteria) this;
		}

		public Criteria andCarColorNotEqualTo(String value) {
			addCriterion("car_color <>", value, "carColor");
			return (Criteria) this;
		}

		public Criteria andCarColorGreaterThan(String value) {
			addCriterion("car_color >", value, "carColor");
			return (Criteria) this;
		}

		public Criteria andCarColorGreaterThanOrEqualTo(String value) {
			addCriterion("car_color >=", value, "carColor");
			return (Criteria) this;
		}

		public Criteria andCarColorLessThan(String value) {
			addCriterion("car_color <", value, "carColor");
			return (Criteria) this;
		}

		public Criteria andCarColorLessThanOrEqualTo(String value) {
			addCriterion("car_color <=", value, "carColor");
			return (Criteria) this;
		}

		public Criteria andCarColorLike(String value) {
			addCriterion("car_color like", value, "carColor");
			return (Criteria) this;
		}

		public Criteria andCarColorNotLike(String value) {
			addCriterion("car_color not like", value, "carColor");
			return (Criteria) this;
		}

		public Criteria andCarColorIn(List<String> values) {
			addCriterion("car_color in", values, "carColor");
			return (Criteria) this;
		}

		public Criteria andCarColorNotIn(List<String> values) {
			addCriterion("car_color not in", values, "carColor");
			return (Criteria) this;
		}

		public Criteria andCarColorBetween(String value1, String value2) {
			addCriterion("car_color between", value1, value2, "carColor");
			return (Criteria) this;
		}

		public Criteria andCarColorNotBetween(String value1, String value2) {
			addCriterion("car_color not between", value1, value2, "carColor");
			return (Criteria) this;
		}

		public Criteria andEngineNumIsNull() {
			addCriterion("engine_num is null");
			return (Criteria) this;
		}

		public Criteria andEngineNumIsNotNull() {
			addCriterion("engine_num is not null");
			return (Criteria) this;
		}

		public Criteria andEngineNumEqualTo(String value) {
			addCriterion("engine_num =", value, "engineNum");
			return (Criteria) this;
		}

		public Criteria andEngineNumNotEqualTo(String value) {
			addCriterion("engine_num <>", value, "engineNum");
			return (Criteria) this;
		}

		public Criteria andEngineNumGreaterThan(String value) {
			addCriterion("engine_num >", value, "engineNum");
			return (Criteria) this;
		}

		public Criteria andEngineNumGreaterThanOrEqualTo(String value) {
			addCriterion("engine_num >=", value, "engineNum");
			return (Criteria) this;
		}

		public Criteria andEngineNumLessThan(String value) {
			addCriterion("engine_num <", value, "engineNum");
			return (Criteria) this;
		}

		public Criteria andEngineNumLessThanOrEqualTo(String value) {
			addCriterion("engine_num <=", value, "engineNum");
			return (Criteria) this;
		}

		public Criteria andEngineNumLike(String value) {
			addCriterion("engine_num like", value, "engineNum");
			return (Criteria) this;
		}

		public Criteria andEngineNumNotLike(String value) {
			addCriterion("engine_num not like", value, "engineNum");
			return (Criteria) this;
		}

		public Criteria andEngineNumIn(List<String> values) {
			addCriterion("engine_num in", values, "engineNum");
			return (Criteria) this;
		}

		public Criteria andEngineNumNotIn(List<String> values) {
			addCriterion("engine_num not in", values, "engineNum");
			return (Criteria) this;
		}

		public Criteria andEngineNumBetween(String value1, String value2) {
			addCriterion("engine_num between", value1, value2, "engineNum");
			return (Criteria) this;
		}

		public Criteria andEngineNumNotBetween(String value1, String value2) {
			addCriterion("engine_num not between", value1, value2, "engineNum");
			return (Criteria) this;
		}

		public Criteria andSaleStatusIsNull() {
			addCriterion("sale_status is null");
			return (Criteria) this;
		}

		public Criteria andSaleStatusIsNotNull() {
			addCriterion("sale_status is not null");
			return (Criteria) this;
		}

		public Criteria andSaleStatusEqualTo(Byte value) {
			addCriterion("sale_status =", value, "saleStatus");
			return (Criteria) this;
		}

		public Criteria andSaleStatusNotEqualTo(Byte value) {
			addCriterion("sale_status <>", value, "saleStatus");
			return (Criteria) this;
		}

		public Criteria andSaleStatusGreaterThan(Byte value) {
			addCriterion("sale_status >", value, "saleStatus");
			return (Criteria) this;
		}

		public Criteria andSaleStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("sale_status >=", value, "saleStatus");
			return (Criteria) this;
		}

		public Criteria andSaleStatusLessThan(Byte value) {
			addCriterion("sale_status <", value, "saleStatus");
			return (Criteria) this;
		}

		public Criteria andSaleStatusLessThanOrEqualTo(Byte value) {
			addCriterion("sale_status <=", value, "saleStatus");
			return (Criteria) this;
		}

		public Criteria andSaleStatusIn(List<Byte> values) {
			addCriterion("sale_status in", values, "saleStatus");
			return (Criteria) this;
		}

		public Criteria andSaleStatusNotIn(List<Byte> values) {
			addCriterion("sale_status not in", values, "saleStatus");
			return (Criteria) this;
		}

		public Criteria andSaleStatusBetween(Byte value1, Byte value2) {
			addCriterion("sale_status between", value1, value2, "saleStatus");
			return (Criteria) this;
		}

		public Criteria andSaleStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("sale_status not between", value1, value2,
					"saleStatus");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table car_info
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 01 15:27:39 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}