package com.ut.scf.pojo.auto;

import java.math.BigDecimal;

public class LimitInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column limit_info.corp_id
     *
     * @mbggenerated Wed Jun 07 19:19:13 CST 2017
     */
    private String corpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column limit_info.max_credit_amount
     *
     * @mbggenerated Wed Jun 07 19:19:13 CST 2017
     */
    private BigDecimal maxCreditAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column limit_info.use_able_credit_amt
     *
     * @mbggenerated Wed Jun 07 19:19:13 CST 2017
     */
    private BigDecimal useAbleCreditAmt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column limit_info.corp_id
     *
     * @return the value of limit_info.corp_id
     *
     * @mbggenerated Wed Jun 07 19:19:13 CST 2017
     */
    public String getCorpId() {
        return corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column limit_info.corp_id
     *
     * @param corpId the value for limit_info.corp_id
     *
     * @mbggenerated Wed Jun 07 19:19:13 CST 2017
     */
    public void setCorpId(String corpId) {
        this.corpId = corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column limit_info.max_credit_amount
     *
     * @return the value of limit_info.max_credit_amount
     *
     * @mbggenerated Wed Jun 07 19:19:13 CST 2017
     */
    public BigDecimal getMaxCreditAmount() {
        return maxCreditAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column limit_info.max_credit_amount
     *
     * @param maxCreditAmount the value for limit_info.max_credit_amount
     *
     * @mbggenerated Wed Jun 07 19:19:13 CST 2017
     */
    public void setMaxCreditAmount(BigDecimal maxCreditAmount) {
        this.maxCreditAmount = maxCreditAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column limit_info.use_able_credit_amt
     *
     * @return the value of limit_info.use_able_credit_amt
     *
     * @mbggenerated Wed Jun 07 19:19:13 CST 2017
     */
    public BigDecimal getUseAbleCreditAmt() {
        return useAbleCreditAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column limit_info.use_able_credit_amt
     *
     * @param useAbleCreditAmt the value for limit_info.use_able_credit_amt
     *
     * @mbggenerated Wed Jun 07 19:19:13 CST 2017
     */
    public void setUseAbleCreditAmt(BigDecimal useAbleCreditAmt) {
        this.useAbleCreditAmt = useAbleCreditAmt;
    }
}