package com.ut.scf.pojo.auto;

import java.math.BigDecimal;
import java.util.Date;

public class DykRepaymentInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dyk_repayment_info.repayment_id
	 * @mbggenerated  Fri Jun 09 14:58:27 CST 2017
	 */
	private String repaymentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dyk_repayment_info.repayment_date
	 * @mbggenerated  Fri Jun 09 14:58:27 CST 2017
	 */
	private Date repaymentDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dyk_repayment_info.repay_sum_amt
	 * @mbggenerated  Fri Jun 09 14:58:27 CST 2017
	 */
	private BigDecimal repaySumAmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dyk_repayment_info.repay_capital_amt
	 * @mbggenerated  Fri Jun 09 14:58:27 CST 2017
	 */
	private BigDecimal repayCapitalAmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dyk_repayment_info.repay_interest_amt
	 * @mbggenerated  Fri Jun 09 14:58:27 CST 2017
	 */
	private BigDecimal repayInterestAmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dyk_repayment_info.act_repay_amt
	 * @mbggenerated  Fri Jun 09 14:58:27 CST 2017
	 */
	private BigDecimal actRepayAmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dyk_repayment_info.car_stolen_certificate
	 * @mbggenerated  Fri Jun 09 14:58:27 CST 2017
	 */
	private String carStolenCertificate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dyk_repayment_info.repayment_type
	 * @mbggenerated  Fri Jun 09 14:58:27 CST 2017
	 */
	private Byte repaymentType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dyk_repayment_info.repayment_id
	 * @return  the value of dyk_repayment_info.repayment_id
	 * @mbggenerated  Fri Jun 09 14:58:27 CST 2017
	 */
	public String getRepaymentId() {
		return repaymentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dyk_repayment_info.repayment_id
	 * @param repaymentId  the value for dyk_repayment_info.repayment_id
	 * @mbggenerated  Fri Jun 09 14:58:27 CST 2017
	 */
	public void setRepaymentId(String repaymentId) {
		this.repaymentId = repaymentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dyk_repayment_info.repayment_date
	 * @return  the value of dyk_repayment_info.repayment_date
	 * @mbggenerated  Fri Jun 09 14:58:27 CST 2017
	 */
	public Date getRepaymentDate() {
		return repaymentDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dyk_repayment_info.repayment_date
	 * @param repaymentDate  the value for dyk_repayment_info.repayment_date
	 * @mbggenerated  Fri Jun 09 14:58:27 CST 2017
	 */
	public void setRepaymentDate(Date repaymentDate) {
		this.repaymentDate = repaymentDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dyk_repayment_info.repay_sum_amt
	 * @return  the value of dyk_repayment_info.repay_sum_amt
	 * @mbggenerated  Fri Jun 09 14:58:27 CST 2017
	 */
	public BigDecimal getRepaySumAmt() {
		return repaySumAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dyk_repayment_info.repay_sum_amt
	 * @param repaySumAmt  the value for dyk_repayment_info.repay_sum_amt
	 * @mbggenerated  Fri Jun 09 14:58:27 CST 2017
	 */
	public void setRepaySumAmt(BigDecimal repaySumAmt) {
		this.repaySumAmt = repaySumAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dyk_repayment_info.repay_capital_amt
	 * @return  the value of dyk_repayment_info.repay_capital_amt
	 * @mbggenerated  Fri Jun 09 14:58:27 CST 2017
	 */
	public BigDecimal getRepayCapitalAmt() {
		return repayCapitalAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dyk_repayment_info.repay_capital_amt
	 * @param repayCapitalAmt  the value for dyk_repayment_info.repay_capital_amt
	 * @mbggenerated  Fri Jun 09 14:58:27 CST 2017
	 */
	public void setRepayCapitalAmt(BigDecimal repayCapitalAmt) {
		this.repayCapitalAmt = repayCapitalAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dyk_repayment_info.repay_interest_amt
	 * @return  the value of dyk_repayment_info.repay_interest_amt
	 * @mbggenerated  Fri Jun 09 14:58:27 CST 2017
	 */
	public BigDecimal getRepayInterestAmt() {
		return repayInterestAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dyk_repayment_info.repay_interest_amt
	 * @param repayInterestAmt  the value for dyk_repayment_info.repay_interest_amt
	 * @mbggenerated  Fri Jun 09 14:58:27 CST 2017
	 */
	public void setRepayInterestAmt(BigDecimal repayInterestAmt) {
		this.repayInterestAmt = repayInterestAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dyk_repayment_info.act_repay_amt
	 * @return  the value of dyk_repayment_info.act_repay_amt
	 * @mbggenerated  Fri Jun 09 14:58:27 CST 2017
	 */
	public BigDecimal getActRepayAmt() {
		return actRepayAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dyk_repayment_info.act_repay_amt
	 * @param actRepayAmt  the value for dyk_repayment_info.act_repay_amt
	 * @mbggenerated  Fri Jun 09 14:58:27 CST 2017
	 */
	public void setActRepayAmt(BigDecimal actRepayAmt) {
		this.actRepayAmt = actRepayAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dyk_repayment_info.car_stolen_certificate
	 * @return  the value of dyk_repayment_info.car_stolen_certificate
	 * @mbggenerated  Fri Jun 09 14:58:27 CST 2017
	 */
	public String getCarStolenCertificate() {
		return carStolenCertificate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dyk_repayment_info.car_stolen_certificate
	 * @param carStolenCertificate  the value for dyk_repayment_info.car_stolen_certificate
	 * @mbggenerated  Fri Jun 09 14:58:27 CST 2017
	 */
	public void setCarStolenCertificate(String carStolenCertificate) {
		this.carStolenCertificate = carStolenCertificate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dyk_repayment_info.repayment_type
	 * @return  the value of dyk_repayment_info.repayment_type
	 * @mbggenerated  Fri Jun 09 14:58:27 CST 2017
	 */
	public Byte getRepaymentType() {
		return repaymentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dyk_repayment_info.repayment_type
	 * @param repaymentType  the value for dyk_repayment_info.repayment_type
	 * @mbggenerated  Fri Jun 09 14:58:27 CST 2017
	 */
	public void setRepaymentType(Byte repaymentType) {
		this.repaymentType = repaymentType;
	}
}