package com.ut.scf.pojo.auto;

import java.math.BigDecimal;

public class DykRate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyk_rate.rec_uid
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    private String recUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyk_rate.product_id
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyk_rate.product_name
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyk_rate.rate_standard
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    private String rateStandard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyk_rate.dyk_rate
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    private BigDecimal dykRate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyk_rate.rec_uid
     *
     * @return the value of dyk_rate.rec_uid
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    public String getRecUid() {
        return recUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyk_rate.rec_uid
     *
     * @param recUid the value for dyk_rate.rec_uid
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    public void setRecUid(String recUid) {
        this.recUid = recUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyk_rate.product_id
     *
     * @return the value of dyk_rate.product_id
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyk_rate.product_id
     *
     * @param productId the value for dyk_rate.product_id
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyk_rate.product_name
     *
     * @return the value of dyk_rate.product_name
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyk_rate.product_name
     *
     * @param productName the value for dyk_rate.product_name
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyk_rate.rate_standard
     *
     * @return the value of dyk_rate.rate_standard
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    public String getRateStandard() {
        return rateStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyk_rate.rate_standard
     *
     * @param rateStandard the value for dyk_rate.rate_standard
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    public void setRateStandard(String rateStandard) {
        this.rateStandard = rateStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyk_rate.dyk_rate
     *
     * @return the value of dyk_rate.dyk_rate
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    public BigDecimal getDykRate() {
        return dykRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyk_rate.dyk_rate
     *
     * @param dykRate the value for dyk_rate.dyk_rate
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    public void setDykRate(BigDecimal dykRate) {
        this.dykRate = dykRate;
    }
}