package com.ut.scf.pojo.auto;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class DykRateExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dyk_rate
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dyk_rate
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dyk_rate
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyk_rate
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    public DykRateExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyk_rate
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyk_rate
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyk_rate
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyk_rate
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyk_rate
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyk_rate
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyk_rate
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyk_rate
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyk_rate
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyk_rate
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dyk_rate
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRecUidIsNull() {
            addCriterion("rec_uid is null");
            return (Criteria) this;
        }

        public Criteria andRecUidIsNotNull() {
            addCriterion("rec_uid is not null");
            return (Criteria) this;
        }

        public Criteria andRecUidEqualTo(String value) {
            addCriterion("rec_uid =", value, "recUid");
            return (Criteria) this;
        }

        public Criteria andRecUidNotEqualTo(String value) {
            addCriterion("rec_uid <>", value, "recUid");
            return (Criteria) this;
        }

        public Criteria andRecUidGreaterThan(String value) {
            addCriterion("rec_uid >", value, "recUid");
            return (Criteria) this;
        }

        public Criteria andRecUidGreaterThanOrEqualTo(String value) {
            addCriterion("rec_uid >=", value, "recUid");
            return (Criteria) this;
        }

        public Criteria andRecUidLessThan(String value) {
            addCriterion("rec_uid <", value, "recUid");
            return (Criteria) this;
        }

        public Criteria andRecUidLessThanOrEqualTo(String value) {
            addCriterion("rec_uid <=", value, "recUid");
            return (Criteria) this;
        }

        public Criteria andRecUidLike(String value) {
            addCriterion("rec_uid like", value, "recUid");
            return (Criteria) this;
        }

        public Criteria andRecUidNotLike(String value) {
            addCriterion("rec_uid not like", value, "recUid");
            return (Criteria) this;
        }

        public Criteria andRecUidIn(List<String> values) {
            addCriterion("rec_uid in", values, "recUid");
            return (Criteria) this;
        }

        public Criteria andRecUidNotIn(List<String> values) {
            addCriterion("rec_uid not in", values, "recUid");
            return (Criteria) this;
        }

        public Criteria andRecUidBetween(String value1, String value2) {
            addCriterion("rec_uid between", value1, value2, "recUid");
            return (Criteria) this;
        }

        public Criteria andRecUidNotBetween(String value1, String value2) {
            addCriterion("rec_uid not between", value1, value2, "recUid");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(String value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(String value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(String value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(String value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(String value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLike(String value) {
            addCriterion("product_id like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotLike(String value) {
            addCriterion("product_id not like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<String> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<String> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(String value1, String value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(String value1, String value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andRateStandardIsNull() {
            addCriterion("rate_standard is null");
            return (Criteria) this;
        }

        public Criteria andRateStandardIsNotNull() {
            addCriterion("rate_standard is not null");
            return (Criteria) this;
        }

        public Criteria andRateStandardEqualTo(String value) {
            addCriterion("rate_standard =", value, "rateStandard");
            return (Criteria) this;
        }

        public Criteria andRateStandardNotEqualTo(String value) {
            addCriterion("rate_standard <>", value, "rateStandard");
            return (Criteria) this;
        }

        public Criteria andRateStandardGreaterThan(String value) {
            addCriterion("rate_standard >", value, "rateStandard");
            return (Criteria) this;
        }

        public Criteria andRateStandardGreaterThanOrEqualTo(String value) {
            addCriterion("rate_standard >=", value, "rateStandard");
            return (Criteria) this;
        }

        public Criteria andRateStandardLessThan(String value) {
            addCriterion("rate_standard <", value, "rateStandard");
            return (Criteria) this;
        }

        public Criteria andRateStandardLessThanOrEqualTo(String value) {
            addCriterion("rate_standard <=", value, "rateStandard");
            return (Criteria) this;
        }

        public Criteria andRateStandardLike(String value) {
            addCriterion("rate_standard like", value, "rateStandard");
            return (Criteria) this;
        }

        public Criteria andRateStandardNotLike(String value) {
            addCriterion("rate_standard not like", value, "rateStandard");
            return (Criteria) this;
        }

        public Criteria andRateStandardIn(List<String> values) {
            addCriterion("rate_standard in", values, "rateStandard");
            return (Criteria) this;
        }

        public Criteria andRateStandardNotIn(List<String> values) {
            addCriterion("rate_standard not in", values, "rateStandard");
            return (Criteria) this;
        }

        public Criteria andRateStandardBetween(String value1, String value2) {
            addCriterion("rate_standard between", value1, value2, "rateStandard");
            return (Criteria) this;
        }

        public Criteria andRateStandardNotBetween(String value1, String value2) {
            addCriterion("rate_standard not between", value1, value2, "rateStandard");
            return (Criteria) this;
        }

        public Criteria andDykRateIsNull() {
            addCriterion("dyk_rate is null");
            return (Criteria) this;
        }

        public Criteria andDykRateIsNotNull() {
            addCriterion("dyk_rate is not null");
            return (Criteria) this;
        }

        public Criteria andDykRateEqualTo(BigDecimal value) {
            addCriterion("dyk_rate =", value, "dykRate");
            return (Criteria) this;
        }

        public Criteria andDykRateNotEqualTo(BigDecimal value) {
            addCriterion("dyk_rate <>", value, "dykRate");
            return (Criteria) this;
        }

        public Criteria andDykRateGreaterThan(BigDecimal value) {
            addCriterion("dyk_rate >", value, "dykRate");
            return (Criteria) this;
        }

        public Criteria andDykRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("dyk_rate >=", value, "dykRate");
            return (Criteria) this;
        }

        public Criteria andDykRateLessThan(BigDecimal value) {
            addCriterion("dyk_rate <", value, "dykRate");
            return (Criteria) this;
        }

        public Criteria andDykRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("dyk_rate <=", value, "dykRate");
            return (Criteria) this;
        }

        public Criteria andDykRateIn(List<BigDecimal> values) {
            addCriterion("dyk_rate in", values, "dykRate");
            return (Criteria) this;
        }

        public Criteria andDykRateNotIn(List<BigDecimal> values) {
            addCriterion("dyk_rate not in", values, "dykRate");
            return (Criteria) this;
        }

        public Criteria andDykRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("dyk_rate between", value1, value2, "dykRate");
            return (Criteria) this;
        }

        public Criteria andDykRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("dyk_rate not between", value1, value2, "dykRate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dyk_rate
     *
     * @mbggenerated do_not_delete_during_merge Thu May 25 19:28:42 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dyk_rate
     *
     * @mbggenerated Thu May 25 19:28:42 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}