package com.ut.scf.pojo.auto;

import java.math.BigDecimal;
import java.util.Date;

public class FinanceInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.finance_id
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	private String financeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.apply_date
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	private Date applyDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.corp_id
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	private String corpId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.finance_rate
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	private BigDecimal financeRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.cash_rate
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	private BigDecimal cashRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.finance_start_date
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	private Date financeStartDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.finance_end_date
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	private Date financeEndDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.finance_amount
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	private BigDecimal financeAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.finance_balance
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	private BigDecimal financeBalance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.expense
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	private BigDecimal expense;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.finance_status
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	private String financeStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.pay_id
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	private String payId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.pay_date
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	private Date payDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.pay_amt
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	private BigDecimal payAmt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.finance_id
	 * @return  the value of finance_info.finance_id
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public String getFinanceId() {
		return financeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.finance_id
	 * @param financeId  the value for finance_info.finance_id
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public void setFinanceId(String financeId) {
		this.financeId = financeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.apply_date
	 * @return  the value of finance_info.apply_date
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public Date getApplyDate() {
		return applyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.apply_date
	 * @param applyDate  the value for finance_info.apply_date
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public void setApplyDate(Date applyDate) {
		this.applyDate = applyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.corp_id
	 * @return  the value of finance_info.corp_id
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public String getCorpId() {
		return corpId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.corp_id
	 * @param corpId  the value for finance_info.corp_id
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public void setCorpId(String corpId) {
		this.corpId = corpId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.finance_rate
	 * @return  the value of finance_info.finance_rate
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public BigDecimal getFinanceRate() {
		return financeRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.finance_rate
	 * @param financeRate  the value for finance_info.finance_rate
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public void setFinanceRate(BigDecimal financeRate) {
		this.financeRate = financeRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.cash_rate
	 * @return  the value of finance_info.cash_rate
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public BigDecimal getCashRate() {
		return cashRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.cash_rate
	 * @param cashRate  the value for finance_info.cash_rate
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public void setCashRate(BigDecimal cashRate) {
		this.cashRate = cashRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.finance_start_date
	 * @return  the value of finance_info.finance_start_date
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public Date getFinanceStartDate() {
		return financeStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.finance_start_date
	 * @param financeStartDate  the value for finance_info.finance_start_date
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public void setFinanceStartDate(Date financeStartDate) {
		this.financeStartDate = financeStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.finance_end_date
	 * @return  the value of finance_info.finance_end_date
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public Date getFinanceEndDate() {
		return financeEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.finance_end_date
	 * @param financeEndDate  the value for finance_info.finance_end_date
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public void setFinanceEndDate(Date financeEndDate) {
		this.financeEndDate = financeEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.finance_amount
	 * @return  the value of finance_info.finance_amount
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public BigDecimal getFinanceAmount() {
		return financeAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.finance_amount
	 * @param financeAmount  the value for finance_info.finance_amount
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public void setFinanceAmount(BigDecimal financeAmount) {
		this.financeAmount = financeAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.finance_balance
	 * @return  the value of finance_info.finance_balance
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public BigDecimal getFinanceBalance() {
		return financeBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.finance_balance
	 * @param financeBalance  the value for finance_info.finance_balance
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public void setFinanceBalance(BigDecimal financeBalance) {
		this.financeBalance = financeBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.expense
	 * @return  the value of finance_info.expense
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public BigDecimal getExpense() {
		return expense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.expense
	 * @param expense  the value for finance_info.expense
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public void setExpense(BigDecimal expense) {
		this.expense = expense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.finance_status
	 * @return  the value of finance_info.finance_status
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public String getFinanceStatus() {
		return financeStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.finance_status
	 * @param financeStatus  the value for finance_info.finance_status
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public void setFinanceStatus(String financeStatus) {
		this.financeStatus = financeStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.pay_id
	 * @return  the value of finance_info.pay_id
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public String getPayId() {
		return payId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.pay_id
	 * @param payId  the value for finance_info.pay_id
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public void setPayId(String payId) {
		this.payId = payId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.pay_date
	 * @return  the value of finance_info.pay_date
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public Date getPayDate() {
		return payDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.pay_date
	 * @param payDate  the value for finance_info.pay_date
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public void setPayDate(Date payDate) {
		this.payDate = payDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.pay_amt
	 * @return  the value of finance_info.pay_amt
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public BigDecimal getPayAmt() {
		return payAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.pay_amt
	 * @param payAmt  the value for finance_info.pay_amt
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	public void setPayAmt(BigDecimal payAmt) {
		this.payAmt = payAmt;
	}
}