package com.ut.scf.pojo.auto;

import java.math.BigDecimal;
import java.util.Date;

public class GuaranteeInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guarantee_info.finance_id
	 * @mbggenerated  Tue Jun 06 17:39:23 CST 2017
	 */
	private String financeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guarantee_info.guarantee_money_rate
	 * @mbggenerated  Tue Jun 06 17:39:23 CST 2017
	 */
	private BigDecimal guaranteeMoneyRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guarantee_info.pay_able_guarantee
	 * @mbggenerated  Tue Jun 06 17:39:23 CST 2017
	 */
	private BigDecimal payAbleGuarantee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guarantee_info.guarantee_pay_date
	 * @mbggenerated  Tue Jun 06 17:39:23 CST 2017
	 */
	private Date guaranteePayDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guarantee_info.pay_act_guarantee
	 * @mbggenerated  Tue Jun 06 17:39:23 CST 2017
	 */
	private BigDecimal payActGuarantee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guarantee_info.guarantee_pay_his
	 * @mbggenerated  Tue Jun 06 17:39:23 CST 2017
	 */
	private String guaranteePayHis;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guarantee_info.guarantee_balance
	 * @mbggenerated  Tue Jun 06 17:39:23 CST 2017
	 */
	private BigDecimal guaranteeBalance;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guarantee_info.finance_id
	 * @return  the value of guarantee_info.finance_id
	 * @mbggenerated  Tue Jun 06 17:39:23 CST 2017
	 */
	public String getFinanceId() {
		return financeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guarantee_info.finance_id
	 * @param financeId  the value for guarantee_info.finance_id
	 * @mbggenerated  Tue Jun 06 17:39:23 CST 2017
	 */
	public void setFinanceId(String financeId) {
		this.financeId = financeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guarantee_info.guarantee_money_rate
	 * @return  the value of guarantee_info.guarantee_money_rate
	 * @mbggenerated  Tue Jun 06 17:39:23 CST 2017
	 */
	public BigDecimal getGuaranteeMoneyRate() {
		return guaranteeMoneyRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guarantee_info.guarantee_money_rate
	 * @param guaranteeMoneyRate  the value for guarantee_info.guarantee_money_rate
	 * @mbggenerated  Tue Jun 06 17:39:23 CST 2017
	 */
	public void setGuaranteeMoneyRate(BigDecimal guaranteeMoneyRate) {
		this.guaranteeMoneyRate = guaranteeMoneyRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guarantee_info.pay_able_guarantee
	 * @return  the value of guarantee_info.pay_able_guarantee
	 * @mbggenerated  Tue Jun 06 17:39:23 CST 2017
	 */
	public BigDecimal getPayAbleGuarantee() {
		return payAbleGuarantee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guarantee_info.pay_able_guarantee
	 * @param payAbleGuarantee  the value for guarantee_info.pay_able_guarantee
	 * @mbggenerated  Tue Jun 06 17:39:23 CST 2017
	 */
	public void setPayAbleGuarantee(BigDecimal payAbleGuarantee) {
		this.payAbleGuarantee = payAbleGuarantee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guarantee_info.guarantee_pay_date
	 * @return  the value of guarantee_info.guarantee_pay_date
	 * @mbggenerated  Tue Jun 06 17:39:23 CST 2017
	 */
	public Date getGuaranteePayDate() {
		return guaranteePayDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guarantee_info.guarantee_pay_date
	 * @param guaranteePayDate  the value for guarantee_info.guarantee_pay_date
	 * @mbggenerated  Tue Jun 06 17:39:23 CST 2017
	 */
	public void setGuaranteePayDate(Date guaranteePayDate) {
		this.guaranteePayDate = guaranteePayDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guarantee_info.pay_act_guarantee
	 * @return  the value of guarantee_info.pay_act_guarantee
	 * @mbggenerated  Tue Jun 06 17:39:23 CST 2017
	 */
	public BigDecimal getPayActGuarantee() {
		return payActGuarantee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guarantee_info.pay_act_guarantee
	 * @param payActGuarantee  the value for guarantee_info.pay_act_guarantee
	 * @mbggenerated  Tue Jun 06 17:39:23 CST 2017
	 */
	public void setPayActGuarantee(BigDecimal payActGuarantee) {
		this.payActGuarantee = payActGuarantee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guarantee_info.guarantee_pay_his
	 * @return  the value of guarantee_info.guarantee_pay_his
	 * @mbggenerated  Tue Jun 06 17:39:23 CST 2017
	 */
	public String getGuaranteePayHis() {
		return guaranteePayHis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guarantee_info.guarantee_pay_his
	 * @param guaranteePayHis  the value for guarantee_info.guarantee_pay_his
	 * @mbggenerated  Tue Jun 06 17:39:23 CST 2017
	 */
	public void setGuaranteePayHis(String guaranteePayHis) {
		this.guaranteePayHis = guaranteePayHis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guarantee_info.guarantee_balance
	 * @return  the value of guarantee_info.guarantee_balance
	 * @mbggenerated  Tue Jun 06 17:39:23 CST 2017
	 */
	public BigDecimal getGuaranteeBalance() {
		return guaranteeBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guarantee_info.guarantee_balance
	 * @param guaranteeBalance  the value for guarantee_info.guarantee_balance
	 * @mbggenerated  Tue Jun 06 17:39:23 CST 2017
	 */
	public void setGuaranteeBalance(BigDecimal guaranteeBalance) {
		this.guaranteeBalance = guaranteeBalance;
	}
}