package com.ut.scf.pojo.auto;

import java.math.BigDecimal;
import java.util.Date;

public class InterestManagement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interest_management.rec_uid
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    private String recUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interest_management.product_id
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interest_management.bett
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    private Byte bett;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interest_management.deduct
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    private Byte deduct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interest_management.reception_date
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    private String receptionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interest_management.interest_rate
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    private BigDecimal interestRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interest_management.cost_rate
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    private BigDecimal costRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interest_management.interest_rate_standard
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    private String interestRateStandard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interest_management.dyk_interest_rate
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    private BigDecimal dykInterestRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interest_management.create_time
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interest_management.create_user_id
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    private String createUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interest_management.rec_uid
     *
     * @return the value of interest_management.rec_uid
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public String getRecUid() {
        return recUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interest_management.rec_uid
     *
     * @param recUid the value for interest_management.rec_uid
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public void setRecUid(String recUid) {
        this.recUid = recUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interest_management.product_id
     *
     * @return the value of interest_management.product_id
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interest_management.product_id
     *
     * @param productId the value for interest_management.product_id
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interest_management.bett
     *
     * @return the value of interest_management.bett
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public Byte getBett() {
        return bett;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interest_management.bett
     *
     * @param bett the value for interest_management.bett
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public void setBett(Byte bett) {
        this.bett = bett;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interest_management.deduct
     *
     * @return the value of interest_management.deduct
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public Byte getDeduct() {
        return deduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interest_management.deduct
     *
     * @param deduct the value for interest_management.deduct
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public void setDeduct(Byte deduct) {
        this.deduct = deduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interest_management.reception_date
     *
     * @return the value of interest_management.reception_date
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public String getReceptionDate() {
        return receptionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interest_management.reception_date
     *
     * @param receptionDate the value for interest_management.reception_date
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public void setReceptionDate(String receptionDate) {
        this.receptionDate = receptionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interest_management.interest_rate
     *
     * @return the value of interest_management.interest_rate
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public BigDecimal getInterestRate() {
        return interestRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interest_management.interest_rate
     *
     * @param interestRate the value for interest_management.interest_rate
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public void setInterestRate(BigDecimal interestRate) {
        this.interestRate = interestRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interest_management.cost_rate
     *
     * @return the value of interest_management.cost_rate
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public BigDecimal getCostRate() {
        return costRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interest_management.cost_rate
     *
     * @param costRate the value for interest_management.cost_rate
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public void setCostRate(BigDecimal costRate) {
        this.costRate = costRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interest_management.interest_rate_standard
     *
     * @return the value of interest_management.interest_rate_standard
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public String getInterestRateStandard() {
        return interestRateStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interest_management.interest_rate_standard
     *
     * @param interestRateStandard the value for interest_management.interest_rate_standard
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public void setInterestRateStandard(String interestRateStandard) {
        this.interestRateStandard = interestRateStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interest_management.dyk_interest_rate
     *
     * @return the value of interest_management.dyk_interest_rate
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public BigDecimal getDykInterestRate() {
        return dykInterestRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interest_management.dyk_interest_rate
     *
     * @param dykInterestRate the value for interest_management.dyk_interest_rate
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public void setDykInterestRate(BigDecimal dykInterestRate) {
        this.dykInterestRate = dykInterestRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interest_management.create_time
     *
     * @return the value of interest_management.create_time
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interest_management.create_time
     *
     * @param createTime the value for interest_management.create_time
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interest_management.create_user_id
     *
     * @return the value of interest_management.create_user_id
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interest_management.create_user_id
     *
     * @param createUserId the value for interest_management.create_user_id
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }
}