package com.ut.scf.pojo.auto;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class OrderBatchInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_batch_info
     *
     * @mbggenerated Tue May 23 19:56:10 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_batch_info
     *
     * @mbggenerated Tue May 23 19:56:10 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_batch_info
     *
     * @mbggenerated Tue May 23 19:56:10 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_batch_info
     *
     * @mbggenerated Tue May 23 19:56:10 CST 2017
     */
    public OrderBatchInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_batch_info
     *
     * @mbggenerated Tue May 23 19:56:10 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_batch_info
     *
     * @mbggenerated Tue May 23 19:56:10 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_batch_info
     *
     * @mbggenerated Tue May 23 19:56:10 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_batch_info
     *
     * @mbggenerated Tue May 23 19:56:10 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_batch_info
     *
     * @mbggenerated Tue May 23 19:56:10 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_batch_info
     *
     * @mbggenerated Tue May 23 19:56:10 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_batch_info
     *
     * @mbggenerated Tue May 23 19:56:10 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_batch_info
     *
     * @mbggenerated Tue May 23 19:56:10 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_batch_info
     *
     * @mbggenerated Tue May 23 19:56:10 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_batch_info
     *
     * @mbggenerated Tue May 23 19:56:10 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_batch_info
     *
     * @mbggenerated Tue May 23 19:56:10 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andOrderBatchIdIsNull() {
            addCriterion("order_batch_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderBatchIdIsNotNull() {
            addCriterion("order_batch_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderBatchIdEqualTo(String value) {
            addCriterion("order_batch_id =", value, "orderBatchId");
            return (Criteria) this;
        }

        public Criteria andOrderBatchIdNotEqualTo(String value) {
            addCriterion("order_batch_id <>", value, "orderBatchId");
            return (Criteria) this;
        }

        public Criteria andOrderBatchIdGreaterThan(String value) {
            addCriterion("order_batch_id >", value, "orderBatchId");
            return (Criteria) this;
        }

        public Criteria andOrderBatchIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_batch_id >=", value, "orderBatchId");
            return (Criteria) this;
        }

        public Criteria andOrderBatchIdLessThan(String value) {
            addCriterion("order_batch_id <", value, "orderBatchId");
            return (Criteria) this;
        }

        public Criteria andOrderBatchIdLessThanOrEqualTo(String value) {
            addCriterion("order_batch_id <=", value, "orderBatchId");
            return (Criteria) this;
        }

        public Criteria andOrderBatchIdLike(String value) {
            addCriterion("order_batch_id like", value, "orderBatchId");
            return (Criteria) this;
        }

        public Criteria andOrderBatchIdNotLike(String value) {
            addCriterion("order_batch_id not like", value, "orderBatchId");
            return (Criteria) this;
        }

        public Criteria andOrderBatchIdIn(List<String> values) {
            addCriterion("order_batch_id in", values, "orderBatchId");
            return (Criteria) this;
        }

        public Criteria andOrderBatchIdNotIn(List<String> values) {
            addCriterion("order_batch_id not in", values, "orderBatchId");
            return (Criteria) this;
        }

        public Criteria andOrderBatchIdBetween(String value1, String value2) {
            addCriterion("order_batch_id between", value1, value2, "orderBatchId");
            return (Criteria) this;
        }

        public Criteria andOrderBatchIdNotBetween(String value1, String value2) {
            addCriterion("order_batch_id not between", value1, value2, "orderBatchId");
            return (Criteria) this;
        }

        public Criteria andOrderTotalNumIsNull() {
            addCriterion("order_total_num is null");
            return (Criteria) this;
        }

        public Criteria andOrderTotalNumIsNotNull() {
            addCriterion("order_total_num is not null");
            return (Criteria) this;
        }

        public Criteria andOrderTotalNumEqualTo(Integer value) {
            addCriterion("order_total_num =", value, "orderTotalNum");
            return (Criteria) this;
        }

        public Criteria andOrderTotalNumNotEqualTo(Integer value) {
            addCriterion("order_total_num <>", value, "orderTotalNum");
            return (Criteria) this;
        }

        public Criteria andOrderTotalNumGreaterThan(Integer value) {
            addCriterion("order_total_num >", value, "orderTotalNum");
            return (Criteria) this;
        }

        public Criteria andOrderTotalNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_total_num >=", value, "orderTotalNum");
            return (Criteria) this;
        }

        public Criteria andOrderTotalNumLessThan(Integer value) {
            addCriterion("order_total_num <", value, "orderTotalNum");
            return (Criteria) this;
        }

        public Criteria andOrderTotalNumLessThanOrEqualTo(Integer value) {
            addCriterion("order_total_num <=", value, "orderTotalNum");
            return (Criteria) this;
        }

        public Criteria andOrderTotalNumIn(List<Integer> values) {
            addCriterion("order_total_num in", values, "orderTotalNum");
            return (Criteria) this;
        }

        public Criteria andOrderTotalNumNotIn(List<Integer> values) {
            addCriterion("order_total_num not in", values, "orderTotalNum");
            return (Criteria) this;
        }

        public Criteria andOrderTotalNumBetween(Integer value1, Integer value2) {
            addCriterion("order_total_num between", value1, value2, "orderTotalNum");
            return (Criteria) this;
        }

        public Criteria andOrderTotalNumNotBetween(Integer value1, Integer value2) {
            addCriterion("order_total_num not between", value1, value2, "orderTotalNum");
            return (Criteria) this;
        }

        public Criteria andOrderTotalAmtIsNull() {
            addCriterion("order_total_amt is null");
            return (Criteria) this;
        }

        public Criteria andOrderTotalAmtIsNotNull() {
            addCriterion("order_total_amt is not null");
            return (Criteria) this;
        }

        public Criteria andOrderTotalAmtEqualTo(BigDecimal value) {
            addCriterion("order_total_amt =", value, "orderTotalAmt");
            return (Criteria) this;
        }

        public Criteria andOrderTotalAmtNotEqualTo(BigDecimal value) {
            addCriterion("order_total_amt <>", value, "orderTotalAmt");
            return (Criteria) this;
        }

        public Criteria andOrderTotalAmtGreaterThan(BigDecimal value) {
            addCriterion("order_total_amt >", value, "orderTotalAmt");
            return (Criteria) this;
        }

        public Criteria andOrderTotalAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("order_total_amt >=", value, "orderTotalAmt");
            return (Criteria) this;
        }

        public Criteria andOrderTotalAmtLessThan(BigDecimal value) {
            addCriterion("order_total_amt <", value, "orderTotalAmt");
            return (Criteria) this;
        }

        public Criteria andOrderTotalAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("order_total_amt <=", value, "orderTotalAmt");
            return (Criteria) this;
        }

        public Criteria andOrderTotalAmtIn(List<BigDecimal> values) {
            addCriterion("order_total_amt in", values, "orderTotalAmt");
            return (Criteria) this;
        }

        public Criteria andOrderTotalAmtNotIn(List<BigDecimal> values) {
            addCriterion("order_total_amt not in", values, "orderTotalAmt");
            return (Criteria) this;
        }

        public Criteria andOrderTotalAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("order_total_amt between", value1, value2, "orderTotalAmt");
            return (Criteria) this;
        }

        public Criteria andOrderTotalAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("order_total_amt not between", value1, value2, "orderTotalAmt");
            return (Criteria) this;
        }

        public Criteria andRecOrderNumIsNull() {
            addCriterion("rec_order_num is null");
            return (Criteria) this;
        }

        public Criteria andRecOrderNumIsNotNull() {
            addCriterion("rec_order_num is not null");
            return (Criteria) this;
        }

        public Criteria andRecOrderNumEqualTo(Integer value) {
            addCriterion("rec_order_num =", value, "recOrderNum");
            return (Criteria) this;
        }

        public Criteria andRecOrderNumNotEqualTo(Integer value) {
            addCriterion("rec_order_num <>", value, "recOrderNum");
            return (Criteria) this;
        }

        public Criteria andRecOrderNumGreaterThan(Integer value) {
            addCriterion("rec_order_num >", value, "recOrderNum");
            return (Criteria) this;
        }

        public Criteria andRecOrderNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("rec_order_num >=", value, "recOrderNum");
            return (Criteria) this;
        }

        public Criteria andRecOrderNumLessThan(Integer value) {
            addCriterion("rec_order_num <", value, "recOrderNum");
            return (Criteria) this;
        }

        public Criteria andRecOrderNumLessThanOrEqualTo(Integer value) {
            addCriterion("rec_order_num <=", value, "recOrderNum");
            return (Criteria) this;
        }

        public Criteria andRecOrderNumIn(List<Integer> values) {
            addCriterion("rec_order_num in", values, "recOrderNum");
            return (Criteria) this;
        }

        public Criteria andRecOrderNumNotIn(List<Integer> values) {
            addCriterion("rec_order_num not in", values, "recOrderNum");
            return (Criteria) this;
        }

        public Criteria andRecOrderNumBetween(Integer value1, Integer value2) {
            addCriterion("rec_order_num between", value1, value2, "recOrderNum");
            return (Criteria) this;
        }

        public Criteria andRecOrderNumNotBetween(Integer value1, Integer value2) {
            addCriterion("rec_order_num not between", value1, value2, "recOrderNum");
            return (Criteria) this;
        }

        public Criteria andRecOrderAmtIsNull() {
            addCriterion("rec_order_amt is null");
            return (Criteria) this;
        }

        public Criteria andRecOrderAmtIsNotNull() {
            addCriterion("rec_order_amt is not null");
            return (Criteria) this;
        }

        public Criteria andRecOrderAmtEqualTo(BigDecimal value) {
            addCriterion("rec_order_amt =", value, "recOrderAmt");
            return (Criteria) this;
        }

        public Criteria andRecOrderAmtNotEqualTo(BigDecimal value) {
            addCriterion("rec_order_amt <>", value, "recOrderAmt");
            return (Criteria) this;
        }

        public Criteria andRecOrderAmtGreaterThan(BigDecimal value) {
            addCriterion("rec_order_amt >", value, "recOrderAmt");
            return (Criteria) this;
        }

        public Criteria andRecOrderAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rec_order_amt >=", value, "recOrderAmt");
            return (Criteria) this;
        }

        public Criteria andRecOrderAmtLessThan(BigDecimal value) {
            addCriterion("rec_order_amt <", value, "recOrderAmt");
            return (Criteria) this;
        }

        public Criteria andRecOrderAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rec_order_amt <=", value, "recOrderAmt");
            return (Criteria) this;
        }

        public Criteria andRecOrderAmtIn(List<BigDecimal> values) {
            addCriterion("rec_order_amt in", values, "recOrderAmt");
            return (Criteria) this;
        }

        public Criteria andRecOrderAmtNotIn(List<BigDecimal> values) {
            addCriterion("rec_order_amt not in", values, "recOrderAmt");
            return (Criteria) this;
        }

        public Criteria andRecOrderAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rec_order_amt between", value1, value2, "recOrderAmt");
            return (Criteria) this;
        }

        public Criteria andRecOrderAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rec_order_amt not between", value1, value2, "recOrderAmt");
            return (Criteria) this;
        }

        public Criteria andRejOrderNumIsNull() {
            addCriterion("rej_order_num is null");
            return (Criteria) this;
        }

        public Criteria andRejOrderNumIsNotNull() {
            addCriterion("rej_order_num is not null");
            return (Criteria) this;
        }

        public Criteria andRejOrderNumEqualTo(Integer value) {
            addCriterion("rej_order_num =", value, "rejOrderNum");
            return (Criteria) this;
        }

        public Criteria andRejOrderNumNotEqualTo(Integer value) {
            addCriterion("rej_order_num <>", value, "rejOrderNum");
            return (Criteria) this;
        }

        public Criteria andRejOrderNumGreaterThan(Integer value) {
            addCriterion("rej_order_num >", value, "rejOrderNum");
            return (Criteria) this;
        }

        public Criteria andRejOrderNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("rej_order_num >=", value, "rejOrderNum");
            return (Criteria) this;
        }

        public Criteria andRejOrderNumLessThan(Integer value) {
            addCriterion("rej_order_num <", value, "rejOrderNum");
            return (Criteria) this;
        }

        public Criteria andRejOrderNumLessThanOrEqualTo(Integer value) {
            addCriterion("rej_order_num <=", value, "rejOrderNum");
            return (Criteria) this;
        }

        public Criteria andRejOrderNumIn(List<Integer> values) {
            addCriterion("rej_order_num in", values, "rejOrderNum");
            return (Criteria) this;
        }

        public Criteria andRejOrderNumNotIn(List<Integer> values) {
            addCriterion("rej_order_num not in", values, "rejOrderNum");
            return (Criteria) this;
        }

        public Criteria andRejOrderNumBetween(Integer value1, Integer value2) {
            addCriterion("rej_order_num between", value1, value2, "rejOrderNum");
            return (Criteria) this;
        }

        public Criteria andRejOrderNumNotBetween(Integer value1, Integer value2) {
            addCriterion("rej_order_num not between", value1, value2, "rejOrderNum");
            return (Criteria) this;
        }

        public Criteria andRejOrderAmtIsNull() {
            addCriterion("rej_order_amt is null");
            return (Criteria) this;
        }

        public Criteria andRejOrderAmtIsNotNull() {
            addCriterion("rej_order_amt is not null");
            return (Criteria) this;
        }

        public Criteria andRejOrderAmtEqualTo(BigDecimal value) {
            addCriterion("rej_order_amt =", value, "rejOrderAmt");
            return (Criteria) this;
        }

        public Criteria andRejOrderAmtNotEqualTo(BigDecimal value) {
            addCriterion("rej_order_amt <>", value, "rejOrderAmt");
            return (Criteria) this;
        }

        public Criteria andRejOrderAmtGreaterThan(BigDecimal value) {
            addCriterion("rej_order_amt >", value, "rejOrderAmt");
            return (Criteria) this;
        }

        public Criteria andRejOrderAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rej_order_amt >=", value, "rejOrderAmt");
            return (Criteria) this;
        }

        public Criteria andRejOrderAmtLessThan(BigDecimal value) {
            addCriterion("rej_order_amt <", value, "rejOrderAmt");
            return (Criteria) this;
        }

        public Criteria andRejOrderAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rej_order_amt <=", value, "rejOrderAmt");
            return (Criteria) this;
        }

        public Criteria andRejOrderAmtIn(List<BigDecimal> values) {
            addCriterion("rej_order_amt in", values, "rejOrderAmt");
            return (Criteria) this;
        }

        public Criteria andRejOrderAmtNotIn(List<BigDecimal> values) {
            addCriterion("rej_order_amt not in", values, "rejOrderAmt");
            return (Criteria) this;
        }

        public Criteria andRejOrderAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rej_order_amt between", value1, value2, "rejOrderAmt");
            return (Criteria) this;
        }

        public Criteria andRejOrderAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rej_order_amt not between", value1, value2, "rejOrderAmt");
            return (Criteria) this;
        }

        public Criteria andCrReqTotalAmtIsNull() {
            addCriterion("cr_req_total_amt is null");
            return (Criteria) this;
        }

        public Criteria andCrReqTotalAmtIsNotNull() {
            addCriterion("cr_req_total_amt is not null");
            return (Criteria) this;
        }

        public Criteria andCrReqTotalAmtEqualTo(BigDecimal value) {
            addCriterion("cr_req_total_amt =", value, "crReqTotalAmt");
            return (Criteria) this;
        }

        public Criteria andCrReqTotalAmtNotEqualTo(BigDecimal value) {
            addCriterion("cr_req_total_amt <>", value, "crReqTotalAmt");
            return (Criteria) this;
        }

        public Criteria andCrReqTotalAmtGreaterThan(BigDecimal value) {
            addCriterion("cr_req_total_amt >", value, "crReqTotalAmt");
            return (Criteria) this;
        }

        public Criteria andCrReqTotalAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cr_req_total_amt >=", value, "crReqTotalAmt");
            return (Criteria) this;
        }

        public Criteria andCrReqTotalAmtLessThan(BigDecimal value) {
            addCriterion("cr_req_total_amt <", value, "crReqTotalAmt");
            return (Criteria) this;
        }

        public Criteria andCrReqTotalAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cr_req_total_amt <=", value, "crReqTotalAmt");
            return (Criteria) this;
        }

        public Criteria andCrReqTotalAmtIn(List<BigDecimal> values) {
            addCriterion("cr_req_total_amt in", values, "crReqTotalAmt");
            return (Criteria) this;
        }

        public Criteria andCrReqTotalAmtNotIn(List<BigDecimal> values) {
            addCriterion("cr_req_total_amt not in", values, "crReqTotalAmt");
            return (Criteria) this;
        }

        public Criteria andCrReqTotalAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cr_req_total_amt between", value1, value2, "crReqTotalAmt");
            return (Criteria) this;
        }

        public Criteria andCrReqTotalAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cr_req_total_amt not between", value1, value2, "crReqTotalAmt");
            return (Criteria) this;
        }

        public Criteria andSyncDateIsNull() {
            addCriterion("sync_date is null");
            return (Criteria) this;
        }

        public Criteria andSyncDateIsNotNull() {
            addCriterion("sync_date is not null");
            return (Criteria) this;
        }

        public Criteria andSyncDateEqualTo(Date value) {
            addCriterionForJDBCDate("sync_date =", value, "syncDate");
            return (Criteria) this;
        }

        public Criteria andSyncDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("sync_date <>", value, "syncDate");
            return (Criteria) this;
        }

        public Criteria andSyncDateGreaterThan(Date value) {
            addCriterionForJDBCDate("sync_date >", value, "syncDate");
            return (Criteria) this;
        }

        public Criteria andSyncDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("sync_date >=", value, "syncDate");
            return (Criteria) this;
        }

        public Criteria andSyncDateLessThan(Date value) {
            addCriterionForJDBCDate("sync_date <", value, "syncDate");
            return (Criteria) this;
        }

        public Criteria andSyncDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("sync_date <=", value, "syncDate");
            return (Criteria) this;
        }

        public Criteria andSyncDateIn(List<Date> values) {
            addCriterionForJDBCDate("sync_date in", values, "syncDate");
            return (Criteria) this;
        }

        public Criteria andSyncDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("sync_date not in", values, "syncDate");
            return (Criteria) this;
        }

        public Criteria andSyncDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("sync_date between", value1, value2, "syncDate");
            return (Criteria) this;
        }

        public Criteria andSyncDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("sync_date not between", value1, value2, "syncDate");
            return (Criteria) this;
        }

        public Criteria andSelDateIsNull() {
            addCriterion("sel_date is null");
            return (Criteria) this;
        }

        public Criteria andSelDateIsNotNull() {
            addCriterion("sel_date is not null");
            return (Criteria) this;
        }

        public Criteria andSelDateEqualTo(Date value) {
            addCriterionForJDBCDate("sel_date =", value, "selDate");
            return (Criteria) this;
        }

        public Criteria andSelDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("sel_date <>", value, "selDate");
            return (Criteria) this;
        }

        public Criteria andSelDateGreaterThan(Date value) {
            addCriterionForJDBCDate("sel_date >", value, "selDate");
            return (Criteria) this;
        }

        public Criteria andSelDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("sel_date >=", value, "selDate");
            return (Criteria) this;
        }

        public Criteria andSelDateLessThan(Date value) {
            addCriterionForJDBCDate("sel_date <", value, "selDate");
            return (Criteria) this;
        }

        public Criteria andSelDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("sel_date <=", value, "selDate");
            return (Criteria) this;
        }

        public Criteria andSelDateIn(List<Date> values) {
            addCriterionForJDBCDate("sel_date in", values, "selDate");
            return (Criteria) this;
        }

        public Criteria andSelDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("sel_date not in", values, "selDate");
            return (Criteria) this;
        }

        public Criteria andSelDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("sel_date between", value1, value2, "selDate");
            return (Criteria) this;
        }

        public Criteria andSelDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("sel_date not between", value1, value2, "selDate");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("note is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("note is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("note =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("note <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("note >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("note >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("note <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("note <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("note like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("note not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("note in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("note not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("note between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("note not between", value1, value2, "note");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_batch_info
     *
     * @mbggenerated do_not_delete_during_merge Tue May 23 19:56:10 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_batch_info
     *
     * @mbggenerated Tue May 23 19:56:10 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}