package com.ut.scf.pojo.auto;

public class RepaymentFinanceBatch {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repayment_finance_batch.rec_uid
	 * @mbggenerated  Sat Jun 10 10:51:56 CST 2017
	 */
	private String recUid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repayment_finance_batch.repayment_id
	 * @mbggenerated  Sat Jun 10 10:51:56 CST 2017
	 */
	private String repaymentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repayment_finance_batch.finance_id
	 * @mbggenerated  Sat Jun 10 10:51:56 CST 2017
	 */
	private String financeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repayment_finance_batch.car_frame_num
	 * @mbggenerated  Sat Jun 10 10:51:56 CST 2017
	 */
	private String carFrameNum;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repayment_finance_batch.rec_uid
	 * @return  the value of repayment_finance_batch.rec_uid
	 * @mbggenerated  Sat Jun 10 10:51:56 CST 2017
	 */
	public String getRecUid() {
		return recUid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repayment_finance_batch.rec_uid
	 * @param recUid  the value for repayment_finance_batch.rec_uid
	 * @mbggenerated  Sat Jun 10 10:51:56 CST 2017
	 */
	public void setRecUid(String recUid) {
		this.recUid = recUid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repayment_finance_batch.repayment_id
	 * @return  the value of repayment_finance_batch.repayment_id
	 * @mbggenerated  Sat Jun 10 10:51:56 CST 2017
	 */
	public String getRepaymentId() {
		return repaymentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repayment_finance_batch.repayment_id
	 * @param repaymentId  the value for repayment_finance_batch.repayment_id
	 * @mbggenerated  Sat Jun 10 10:51:56 CST 2017
	 */
	public void setRepaymentId(String repaymentId) {
		this.repaymentId = repaymentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repayment_finance_batch.finance_id
	 * @return  the value of repayment_finance_batch.finance_id
	 * @mbggenerated  Sat Jun 10 10:51:56 CST 2017
	 */
	public String getFinanceId() {
		return financeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repayment_finance_batch.finance_id
	 * @param financeId  the value for repayment_finance_batch.finance_id
	 * @mbggenerated  Sat Jun 10 10:51:56 CST 2017
	 */
	public void setFinanceId(String financeId) {
		this.financeId = financeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repayment_finance_batch.car_frame_num
	 * @return  the value of repayment_finance_batch.car_frame_num
	 * @mbggenerated  Sat Jun 10 10:51:56 CST 2017
	 */
	public String getCarFrameNum() {
		return carFrameNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repayment_finance_batch.car_frame_num
	 * @param carFrameNum  the value for repayment_finance_batch.car_frame_num
	 * @mbggenerated  Sat Jun 10 10:51:56 CST 2017
	 */
	public void setCarFrameNum(String carFrameNum) {
		this.carFrameNum = carFrameNum;
	}
}