package com.ut.scf.pojo.auto;

import java.util.Date;

public class SysBizLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_biz_log.log_id
     *
     * @mbggenerated Tue May 16 17:25:29 CST 2017
     */
    private String logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_biz_log.user_id
     *
     * @mbggenerated Tue May 16 17:25:29 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_biz_log.interface_id
     *
     * @mbggenerated Tue May 16 17:25:29 CST 2017
     */
    private String interfaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_biz_log.ip
     *
     * @mbggenerated Tue May 16 17:25:29 CST 2017
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_biz_log.content
     *
     * @mbggenerated Tue May 16 17:25:29 CST 2017
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_biz_log.oper_time
     *
     * @mbggenerated Tue May 16 17:25:29 CST 2017
     */
    private Date operTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_biz_log.log_id
     *
     * @return the value of sys_biz_log.log_id
     *
     * @mbggenerated Tue May 16 17:25:29 CST 2017
     */
    public String getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_biz_log.log_id
     *
     * @param logId the value for sys_biz_log.log_id
     *
     * @mbggenerated Tue May 16 17:25:29 CST 2017
     */
    public void setLogId(String logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_biz_log.user_id
     *
     * @return the value of sys_biz_log.user_id
     *
     * @mbggenerated Tue May 16 17:25:29 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_biz_log.user_id
     *
     * @param userId the value for sys_biz_log.user_id
     *
     * @mbggenerated Tue May 16 17:25:29 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_biz_log.interface_id
     *
     * @return the value of sys_biz_log.interface_id
     *
     * @mbggenerated Tue May 16 17:25:29 CST 2017
     */
    public String getInterfaceId() {
        return interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_biz_log.interface_id
     *
     * @param interfaceId the value for sys_biz_log.interface_id
     *
     * @mbggenerated Tue May 16 17:25:29 CST 2017
     */
    public void setInterfaceId(String interfaceId) {
        this.interfaceId = interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_biz_log.ip
     *
     * @return the value of sys_biz_log.ip
     *
     * @mbggenerated Tue May 16 17:25:29 CST 2017
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_biz_log.ip
     *
     * @param ip the value for sys_biz_log.ip
     *
     * @mbggenerated Tue May 16 17:25:29 CST 2017
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_biz_log.content
     *
     * @return the value of sys_biz_log.content
     *
     * @mbggenerated Tue May 16 17:25:29 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_biz_log.content
     *
     * @param content the value for sys_biz_log.content
     *
     * @mbggenerated Tue May 16 17:25:29 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_biz_log.oper_time
     *
     * @return the value of sys_biz_log.oper_time
     *
     * @mbggenerated Tue May 16 17:25:29 CST 2017
     */
    public Date getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_biz_log.oper_time
     *
     * @param operTime the value for sys_biz_log.oper_time
     *
     * @mbggenerated Tue May 16 17:25:29 CST 2017
     */
    public void setOperTime(Date operTime) {
        this.operTime = operTime;
    }
}