package com.ut.scf.pojo.auto;

import java.util.Date;

public class SysUserRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_role.rec_uid
	 * @mbggenerated  Thu May 18 13:27:13 CST 2017
	 */
	private String recUid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_role.user_id
	 * @mbggenerated  Thu May 18 13:27:13 CST 2017
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_role.role_id
	 * @mbggenerated  Thu May 18 13:27:13 CST 2017
	 */
	private String roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_role.create_time
	 * @mbggenerated  Thu May 18 13:27:13 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_role.status
	 * @mbggenerated  Thu May 18 13:27:13 CST 2017
	 */
	private Byte status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_role.rec_uid
	 * @return  the value of sys_user_role.rec_uid
	 * @mbggenerated  Thu May 18 13:27:13 CST 2017
	 */
	public String getRecUid() {
		return recUid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_role.rec_uid
	 * @param recUid  the value for sys_user_role.rec_uid
	 * @mbggenerated  Thu May 18 13:27:13 CST 2017
	 */
	public void setRecUid(String recUid) {
		this.recUid = recUid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_role.user_id
	 * @return  the value of sys_user_role.user_id
	 * @mbggenerated  Thu May 18 13:27:13 CST 2017
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_role.user_id
	 * @param userId  the value for sys_user_role.user_id
	 * @mbggenerated  Thu May 18 13:27:13 CST 2017
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_role.role_id
	 * @return  the value of sys_user_role.role_id
	 * @mbggenerated  Thu May 18 13:27:13 CST 2017
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_role.role_id
	 * @param roleId  the value for sys_user_role.role_id
	 * @mbggenerated  Thu May 18 13:27:13 CST 2017
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_role.create_time
	 * @return  the value of sys_user_role.create_time
	 * @mbggenerated  Thu May 18 13:27:13 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_role.create_time
	 * @param createTime  the value for sys_user_role.create_time
	 * @mbggenerated  Thu May 18 13:27:13 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_role.status
	 * @return  the value of sys_user_role.status
	 * @mbggenerated  Thu May 18 13:27:13 CST 2017
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_role.status
	 * @param status  the value for sys_user_role.status
	 * @mbggenerated  Thu May 18 13:27:13 CST 2017
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}
}