package com.ut.scf.pojo.auto;

public class SysType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_type.type_id
     *
     * @mbggenerated Tue May 16 16:37:24 CST 2017
     */
    private Short typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_type.type_name
     *
     * @mbggenerated Tue May 16 16:37:24 CST 2017
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_type.type_desc
     *
     * @mbggenerated Tue May 16 16:37:24 CST 2017
     */
    private String typeDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_type.type_id
     *
     * @return the value of sys_type.type_id
     *
     * @mbggenerated Tue May 16 16:37:24 CST 2017
     */
    public Short getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_type.type_id
     *
     * @param typeId the value for sys_type.type_id
     *
     * @mbggenerated Tue May 16 16:37:24 CST 2017
     */
    public void setTypeId(Short typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_type.type_name
     *
     * @return the value of sys_type.type_name
     *
     * @mbggenerated Tue May 16 16:37:24 CST 2017
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_type.type_name
     *
     * @param typeName the value for sys_type.type_name
     *
     * @mbggenerated Tue May 16 16:37:24 CST 2017
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_type.type_desc
     *
     * @return the value of sys_type.type_desc
     *
     * @mbggenerated Tue May 16 16:37:24 CST 2017
     */
    public String getTypeDesc() {
        return typeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_type.type_desc
     *
     * @param typeDesc the value for sys_type.type_desc
     *
     * @mbggenerated Tue May 16 16:37:24 CST 2017
     */
    public void setTypeDesc(String typeDesc) {
        this.typeDesc = typeDesc;
    }
}