package com.ut.scf.dao.auto;

import com.ut.scf.pojo.auto.CarInfo;
import com.ut.scf.pojo.auto.CarInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CarInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	int countByExample(CarInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	int deleteByExample(CarInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	int deleteByPrimaryKey(String carFrameNum);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	int insert(CarInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	int insertSelective(CarInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	List<CarInfo> selectByExample(CarInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	CarInfo selectByPrimaryKey(String carFrameNum);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	int updateByExampleSelective(@Param("record") CarInfo record,
			@Param("example") CarInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	int updateByExample(@Param("record") CarInfo record,
			@Param("example") CarInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	int updateByPrimaryKeySelective(CarInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_info
	 * @mbggenerated  Mon Jun 05 16:28:38 CST 2017
	 */
	int updateByPrimaryKey(CarInfo record);
}