package com.ut.scf.pojo;

import java.util.Date;

public class SysFuncInterface {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_func_interface.interface_id
	 * @mbggenerated  Mon Sep 19 16:00:59 CST 2016
	 */
	private String interfaceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_func_interface.interface_name
	 * @mbggenerated  Mon Sep 19 16:00:59 CST 2016
	 */
	private String interfaceName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_func_interface.path
	 * @mbggenerated  Mon Sep 19 16:00:59 CST 2016
	 */
	private String path;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_func_interface.method
	 * @mbggenerated  Mon Sep 19 16:00:59 CST 2016
	 */
	private String method;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_func_interface.access_status
	 * @mbggenerated  Mon Sep 19 16:00:59 CST 2016
	 */
	private Byte accessStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_func_interface.note
	 * @mbggenerated  Mon Sep 19 16:00:59 CST 2016
	 */
	private String note;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_func_interface.create_time
	 * @mbggenerated  Mon Sep 19 16:00:59 CST 2016
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_func_interface.interface_id
	 * @return  the value of sys_func_interface.interface_id
	 * @mbggenerated  Mon Sep 19 16:00:59 CST 2016
	 */
	public String getInterfaceId() {
		return interfaceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_func_interface.interface_id
	 * @param interfaceId  the value for sys_func_interface.interface_id
	 * @mbggenerated  Mon Sep 19 16:00:59 CST 2016
	 */
	public void setInterfaceId(String interfaceId) {
		this.interfaceId = interfaceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_func_interface.interface_name
	 * @return  the value of sys_func_interface.interface_name
	 * @mbggenerated  Mon Sep 19 16:00:59 CST 2016
	 */
	public String getInterfaceName() {
		return interfaceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_func_interface.interface_name
	 * @param interfaceName  the value for sys_func_interface.interface_name
	 * @mbggenerated  Mon Sep 19 16:00:59 CST 2016
	 */
	public void setInterfaceName(String interfaceName) {
		this.interfaceName = interfaceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_func_interface.path
	 * @return  the value of sys_func_interface.path
	 * @mbggenerated  Mon Sep 19 16:00:59 CST 2016
	 */
	public String getPath() {
		return path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_func_interface.path
	 * @param path  the value for sys_func_interface.path
	 * @mbggenerated  Mon Sep 19 16:00:59 CST 2016
	 */
	public void setPath(String path) {
		this.path = path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_func_interface.method
	 * @return  the value of sys_func_interface.method
	 * @mbggenerated  Mon Sep 19 16:00:59 CST 2016
	 */
	public String getMethod() {
		return method;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_func_interface.method
	 * @param method  the value for sys_func_interface.method
	 * @mbggenerated  Mon Sep 19 16:00:59 CST 2016
	 */
	public void setMethod(String method) {
		this.method = method;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_func_interface.access_status
	 * @return  the value of sys_func_interface.access_status
	 * @mbggenerated  Mon Sep 19 16:00:59 CST 2016
	 */
	public Byte getAccessStatus() {
		return accessStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_func_interface.access_status
	 * @param accessStatus  the value for sys_func_interface.access_status
	 * @mbggenerated  Mon Sep 19 16:00:59 CST 2016
	 */
	public void setAccessStatus(Byte accessStatus) {
		this.accessStatus = accessStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_func_interface.note
	 * @return  the value of sys_func_interface.note
	 * @mbggenerated  Mon Sep 19 16:00:59 CST 2016
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_func_interface.note
	 * @param note  the value for sys_func_interface.note
	 * @mbggenerated  Mon Sep 19 16:00:59 CST 2016
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_func_interface.create_time
	 * @return  the value of sys_func_interface.create_time
	 * @mbggenerated  Mon Sep 19 16:00:59 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_func_interface.create_time
	 * @param createTime  the value for sys_func_interface.create_time
	 * @mbggenerated  Mon Sep 19 16:00:59 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}