package com.ut.scf.dao.auto;

import com.ut.scf.pojo.auto.AgencySequence;
import com.ut.scf.pojo.auto.AgencySequenceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AgencySequenceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agency_sequence
	 * @mbggenerated  Mon Jun 12 18:00:40 CST 2017
	 */
	int countByExample(AgencySequenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agency_sequence
	 * @mbggenerated  Mon Jun 12 18:00:40 CST 2017
	 */
	int deleteByExample(AgencySequenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agency_sequence
	 * @mbggenerated  Mon Jun 12 18:00:40 CST 2017
	 */
	int deleteByPrimaryKey(String corpId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agency_sequence
	 * @mbggenerated  Mon Jun 12 18:00:40 CST 2017
	 */
	int insert(AgencySequence record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agency_sequence
	 * @mbggenerated  Mon Jun 12 18:00:40 CST 2017
	 */
	int insertSelective(AgencySequence record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agency_sequence
	 * @mbggenerated  Mon Jun 12 18:00:40 CST 2017
	 */
	List<AgencySequence> selectByExample(AgencySequenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agency_sequence
	 * @mbggenerated  Mon Jun 12 18:00:40 CST 2017
	 */
	AgencySequence selectByPrimaryKey(String corpId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agency_sequence
	 * @mbggenerated  Mon Jun 12 18:00:40 CST 2017
	 */
	int updateByExampleSelective(@Param("record") AgencySequence record,
			@Param("example") AgencySequenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agency_sequence
	 * @mbggenerated  Mon Jun 12 18:00:40 CST 2017
	 */
	int updateByExample(@Param("record") AgencySequence record,
			@Param("example") AgencySequenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agency_sequence
	 * @mbggenerated  Mon Jun 12 18:00:40 CST 2017
	 */
	int updateByPrimaryKeySelective(AgencySequence record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agency_sequence
	 * @mbggenerated  Mon Jun 12 18:00:40 CST 2017
	 */
	int updateByPrimaryKey(AgencySequence record);
}