package com.ut.scf.pojo.auto;

import java.util.Date;

public class InternalAnnouncement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_announcement.rec_uid
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    private String recUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_announcement.corp_id
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    private String corpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_announcement.title
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_announcement.user_id
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_announcement.announcement_content
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    private String announcementContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_announcement.release_date
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    private Date releaseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_announcement.attachment_url
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    private String attachmentUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_announcement.create_user_id
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_announcement.create_time
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_announcement.rec_uid
     *
     * @return the value of internal_announcement.rec_uid
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    public String getRecUid() {
        return recUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_announcement.rec_uid
     *
     * @param recUid the value for internal_announcement.rec_uid
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    public void setRecUid(String recUid) {
        this.recUid = recUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_announcement.corp_id
     *
     * @return the value of internal_announcement.corp_id
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    public String getCorpId() {
        return corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_announcement.corp_id
     *
     * @param corpId the value for internal_announcement.corp_id
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    public void setCorpId(String corpId) {
        this.corpId = corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_announcement.title
     *
     * @return the value of internal_announcement.title
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_announcement.title
     *
     * @param title the value for internal_announcement.title
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_announcement.user_id
     *
     * @return the value of internal_announcement.user_id
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_announcement.user_id
     *
     * @param userId the value for internal_announcement.user_id
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_announcement.announcement_content
     *
     * @return the value of internal_announcement.announcement_content
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    public String getAnnouncementContent() {
        return announcementContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_announcement.announcement_content
     *
     * @param announcementContent the value for internal_announcement.announcement_content
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    public void setAnnouncementContent(String announcementContent) {
        this.announcementContent = announcementContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_announcement.release_date
     *
     * @return the value of internal_announcement.release_date
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    public Date getReleaseDate() {
        return releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_announcement.release_date
     *
     * @param releaseDate the value for internal_announcement.release_date
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_announcement.attachment_url
     *
     * @return the value of internal_announcement.attachment_url
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    public String getAttachmentUrl() {
        return attachmentUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_announcement.attachment_url
     *
     * @param attachmentUrl the value for internal_announcement.attachment_url
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    public void setAttachmentUrl(String attachmentUrl) {
        this.attachmentUrl = attachmentUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_announcement.create_user_id
     *
     * @return the value of internal_announcement.create_user_id
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_announcement.create_user_id
     *
     * @param createUserId the value for internal_announcement.create_user_id
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_announcement.create_time
     *
     * @return the value of internal_announcement.create_time
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_announcement.create_time
     *
     * @param createTime the value for internal_announcement.create_time
     *
     * @mbggenerated Wed May 17 14:24:27 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}