package com.ut.scf.pojo.auto;


public class GuaranteeMoneyManagement {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guarantee_money_management.product_id
	 * @mbggenerated  Mon May 22 16:49:27 CST 2017
	 */
	private String productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guarantee_money_management.product_name
	 * @mbggenerated  Mon May 22 16:49:27 CST 2017
	 */
	private String productName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guarantee_money_management.guarantee_money_rate
	 * @mbggenerated  Mon May 22 16:49:27 CST 2017
	 */
	private Double guaranteeMoneyRate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guarantee_money_management.product_id
	 * @return  the value of guarantee_money_management.product_id
	 * @mbggenerated  Mon May 22 16:49:27 CST 2017
	 */
	public String getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guarantee_money_management.product_id
	 * @param productId  the value for guarantee_money_management.product_id
	 * @mbggenerated  Mon May 22 16:49:27 CST 2017
	 */
	public void setProductId(String productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guarantee_money_management.product_name
	 * @return  the value of guarantee_money_management.product_name
	 * @mbggenerated  Mon May 22 16:49:27 CST 2017
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guarantee_money_management.product_name
	 * @param productName  the value for guarantee_money_management.product_name
	 * @mbggenerated  Mon May 22 16:49:27 CST 2017
	 */
	public void setProductName(String productName) {
		this.productName = productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guarantee_money_management.guarantee_money_rate
	 * @return  the value of guarantee_money_management.guarantee_money_rate
	 * @mbggenerated  Mon May 22 16:49:27 CST 2017
	 */
	public Double getGuaranteeMoneyRate() {
		return guaranteeMoneyRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guarantee_money_management.guarantee_money_rate
	 * @param guaranteeMoneyRate  the value for guarantee_money_management.guarantee_money_rate
	 * @mbggenerated  Mon May 22 16:49:27 CST 2017
	 */
	public void setGuaranteeMoneyRate(Double guaranteeMoneyRate) {
		this.guaranteeMoneyRate = guaranteeMoneyRate;
	}
}