package com.ut.scf.dao.auto;

import com.ut.scf.pojo.auto.RevenueManagement;
import com.ut.scf.pojo.auto.RevenueManagementExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RevenueManagementMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue_management
	 * @mbggenerated  Fri Jun 09 14:58:13 CST 2017
	 */
	int countByExample(RevenueManagementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue_management
	 * @mbggenerated  Fri Jun 09 14:58:13 CST 2017
	 */
	int deleteByExample(RevenueManagementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue_management
	 * @mbggenerated  Fri Jun 09 14:58:13 CST 2017
	 */
	int deleteByPrimaryKey(String financeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue_management
	 * @mbggenerated  Fri Jun 09 14:58:13 CST 2017
	 */
	int insert(RevenueManagement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue_management
	 * @mbggenerated  Fri Jun 09 14:58:13 CST 2017
	 */
	int insertSelective(RevenueManagement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue_management
	 * @mbggenerated  Fri Jun 09 14:58:13 CST 2017
	 */
	List<RevenueManagement> selectByExample(RevenueManagementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue_management
	 * @mbggenerated  Fri Jun 09 14:58:13 CST 2017
	 */
	RevenueManagement selectByPrimaryKey(String financeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue_management
	 * @mbggenerated  Fri Jun 09 14:58:13 CST 2017
	 */
	int updateByExampleSelective(@Param("record") RevenueManagement record,
			@Param("example") RevenueManagementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue_management
	 * @mbggenerated  Fri Jun 09 14:58:13 CST 2017
	 */
	int updateByExample(@Param("record") RevenueManagement record,
			@Param("example") RevenueManagementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue_management
	 * @mbggenerated  Fri Jun 09 14:58:13 CST 2017
	 */
	int updateByPrimaryKeySelective(RevenueManagement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue_management
	 * @mbggenerated  Fri Jun 09 14:58:13 CST 2017
	 */
	int updateByPrimaryKey(RevenueManagement record);
}