package com.ut.scf.pojo.auto;

import java.math.BigDecimal;
import java.util.Date;

public class OrderInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.order_id
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.product_id
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	private String productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.product_name
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	private String productName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.product_amt
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	private BigDecimal productAmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.period
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	private Byte period;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.loan
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	private BigDecimal loan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.seller_id
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	private String sellerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.seller_name
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	private String sellerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.cr_req_amt
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	private BigDecimal crReqAmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.start_pay_amt
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	private BigDecimal startPayAmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.pay_m
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	private BigDecimal payM;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.start_pay_day
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	private Date startPayDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.order_status
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	private Byte orderStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.order_batch_id
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	private String orderBatchId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.stu_id
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	private String stuId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.order_id
	 * @return  the value of order_info.order_id
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.order_id
	 * @param orderId  the value for order_info.order_id
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.product_id
	 * @return  the value of order_info.product_id
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public String getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.product_id
	 * @param productId  the value for order_info.product_id
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public void setProductId(String productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.product_name
	 * @return  the value of order_info.product_name
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.product_name
	 * @param productName  the value for order_info.product_name
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public void setProductName(String productName) {
		this.productName = productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.product_amt
	 * @return  the value of order_info.product_amt
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public BigDecimal getProductAmt() {
		return productAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.product_amt
	 * @param productAmt  the value for order_info.product_amt
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public void setProductAmt(BigDecimal productAmt) {
		this.productAmt = productAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.period
	 * @return  the value of order_info.period
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public Byte getPeriod() {
		return period;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.period
	 * @param period  the value for order_info.period
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public void setPeriod(Byte period) {
		this.period = period;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.loan
	 * @return  the value of order_info.loan
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public BigDecimal getLoan() {
		return loan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.loan
	 * @param loan  the value for order_info.loan
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public void setLoan(BigDecimal loan) {
		this.loan = loan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.seller_id
	 * @return  the value of order_info.seller_id
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public String getSellerId() {
		return sellerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.seller_id
	 * @param sellerId  the value for order_info.seller_id
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public void setSellerId(String sellerId) {
		this.sellerId = sellerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.seller_name
	 * @return  the value of order_info.seller_name
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public String getSellerName() {
		return sellerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.seller_name
	 * @param sellerName  the value for order_info.seller_name
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public void setSellerName(String sellerName) {
		this.sellerName = sellerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.cr_req_amt
	 * @return  the value of order_info.cr_req_amt
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public BigDecimal getCrReqAmt() {
		return crReqAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.cr_req_amt
	 * @param crReqAmt  the value for order_info.cr_req_amt
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public void setCrReqAmt(BigDecimal crReqAmt) {
		this.crReqAmt = crReqAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.start_pay_amt
	 * @return  the value of order_info.start_pay_amt
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public BigDecimal getStartPayAmt() {
		return startPayAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.start_pay_amt
	 * @param startPayAmt  the value for order_info.start_pay_amt
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public void setStartPayAmt(BigDecimal startPayAmt) {
		this.startPayAmt = startPayAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.pay_m
	 * @return  the value of order_info.pay_m
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public BigDecimal getPayM() {
		return payM;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.pay_m
	 * @param payM  the value for order_info.pay_m
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public void setPayM(BigDecimal payM) {
		this.payM = payM;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.start_pay_day
	 * @return  the value of order_info.start_pay_day
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public Date getStartPayDay() {
		return startPayDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.start_pay_day
	 * @param startPayDay  the value for order_info.start_pay_day
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public void setStartPayDay(Date startPayDay) {
		this.startPayDay = startPayDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.order_status
	 * @return  the value of order_info.order_status
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public Byte getOrderStatus() {
		return orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.order_status
	 * @param orderStatus  the value for order_info.order_status
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public void setOrderStatus(Byte orderStatus) {
		this.orderStatus = orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.order_batch_id
	 * @return  the value of order_info.order_batch_id
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public String getOrderBatchId() {
		return orderBatchId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.order_batch_id
	 * @param orderBatchId  the value for order_info.order_batch_id
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public void setOrderBatchId(String orderBatchId) {
		this.orderBatchId = orderBatchId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.stu_id
	 * @return  the value of order_info.stu_id
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public String getStuId() {
		return stuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.stu_id
	 * @param stuId  the value for order_info.stu_id
	 * @mbggenerated  Mon Jun 12 17:31:18 CST 2017
	 */
	public void setStuId(String stuId) {
		this.stuId = stuId;
	}
}