package com.ut.scf.pojo.auto;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class InterestManagementExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public InterestManagementExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRecUidIsNull() {
            addCriterion("rec_uid is null");
            return (Criteria) this;
        }

        public Criteria andRecUidIsNotNull() {
            addCriterion("rec_uid is not null");
            return (Criteria) this;
        }

        public Criteria andRecUidEqualTo(String value) {
            addCriterion("rec_uid =", value, "recUid");
            return (Criteria) this;
        }

        public Criteria andRecUidNotEqualTo(String value) {
            addCriterion("rec_uid <>", value, "recUid");
            return (Criteria) this;
        }

        public Criteria andRecUidGreaterThan(String value) {
            addCriterion("rec_uid >", value, "recUid");
            return (Criteria) this;
        }

        public Criteria andRecUidGreaterThanOrEqualTo(String value) {
            addCriterion("rec_uid >=", value, "recUid");
            return (Criteria) this;
        }

        public Criteria andRecUidLessThan(String value) {
            addCriterion("rec_uid <", value, "recUid");
            return (Criteria) this;
        }

        public Criteria andRecUidLessThanOrEqualTo(String value) {
            addCriterion("rec_uid <=", value, "recUid");
            return (Criteria) this;
        }

        public Criteria andRecUidLike(String value) {
            addCriterion("rec_uid like", value, "recUid");
            return (Criteria) this;
        }

        public Criteria andRecUidNotLike(String value) {
            addCriterion("rec_uid not like", value, "recUid");
            return (Criteria) this;
        }

        public Criteria andRecUidIn(List<String> values) {
            addCriterion("rec_uid in", values, "recUid");
            return (Criteria) this;
        }

        public Criteria andRecUidNotIn(List<String> values) {
            addCriterion("rec_uid not in", values, "recUid");
            return (Criteria) this;
        }

        public Criteria andRecUidBetween(String value1, String value2) {
            addCriterion("rec_uid between", value1, value2, "recUid");
            return (Criteria) this;
        }

        public Criteria andRecUidNotBetween(String value1, String value2) {
            addCriterion("rec_uid not between", value1, value2, "recUid");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(String value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(String value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(String value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(String value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(String value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLike(String value) {
            addCriterion("product_id like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotLike(String value) {
            addCriterion("product_id not like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<String> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<String> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(String value1, String value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(String value1, String value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andBettIsNull() {
            addCriterion("bett is null");
            return (Criteria) this;
        }

        public Criteria andBettIsNotNull() {
            addCriterion("bett is not null");
            return (Criteria) this;
        }

        public Criteria andBettEqualTo(Byte value) {
            addCriterion("bett =", value, "bett");
            return (Criteria) this;
        }

        public Criteria andBettNotEqualTo(Byte value) {
            addCriterion("bett <>", value, "bett");
            return (Criteria) this;
        }

        public Criteria andBettGreaterThan(Byte value) {
            addCriterion("bett >", value, "bett");
            return (Criteria) this;
        }

        public Criteria andBettGreaterThanOrEqualTo(Byte value) {
            addCriterion("bett >=", value, "bett");
            return (Criteria) this;
        }

        public Criteria andBettLessThan(Byte value) {
            addCriterion("bett <", value, "bett");
            return (Criteria) this;
        }

        public Criteria andBettLessThanOrEqualTo(Byte value) {
            addCriterion("bett <=", value, "bett");
            return (Criteria) this;
        }

        public Criteria andBettIn(List<Byte> values) {
            addCriterion("bett in", values, "bett");
            return (Criteria) this;
        }

        public Criteria andBettNotIn(List<Byte> values) {
            addCriterion("bett not in", values, "bett");
            return (Criteria) this;
        }

        public Criteria andBettBetween(Byte value1, Byte value2) {
            addCriterion("bett between", value1, value2, "bett");
            return (Criteria) this;
        }

        public Criteria andBettNotBetween(Byte value1, Byte value2) {
            addCriterion("bett not between", value1, value2, "bett");
            return (Criteria) this;
        }

        public Criteria andDeductIsNull() {
            addCriterion("deduct is null");
            return (Criteria) this;
        }

        public Criteria andDeductIsNotNull() {
            addCriterion("deduct is not null");
            return (Criteria) this;
        }

        public Criteria andDeductEqualTo(Byte value) {
            addCriterion("deduct =", value, "deduct");
            return (Criteria) this;
        }

        public Criteria andDeductNotEqualTo(Byte value) {
            addCriterion("deduct <>", value, "deduct");
            return (Criteria) this;
        }

        public Criteria andDeductGreaterThan(Byte value) {
            addCriterion("deduct >", value, "deduct");
            return (Criteria) this;
        }

        public Criteria andDeductGreaterThanOrEqualTo(Byte value) {
            addCriterion("deduct >=", value, "deduct");
            return (Criteria) this;
        }

        public Criteria andDeductLessThan(Byte value) {
            addCriterion("deduct <", value, "deduct");
            return (Criteria) this;
        }

        public Criteria andDeductLessThanOrEqualTo(Byte value) {
            addCriterion("deduct <=", value, "deduct");
            return (Criteria) this;
        }

        public Criteria andDeductIn(List<Byte> values) {
            addCriterion("deduct in", values, "deduct");
            return (Criteria) this;
        }

        public Criteria andDeductNotIn(List<Byte> values) {
            addCriterion("deduct not in", values, "deduct");
            return (Criteria) this;
        }

        public Criteria andDeductBetween(Byte value1, Byte value2) {
            addCriterion("deduct between", value1, value2, "deduct");
            return (Criteria) this;
        }

        public Criteria andDeductNotBetween(Byte value1, Byte value2) {
            addCriterion("deduct not between", value1, value2, "deduct");
            return (Criteria) this;
        }

        public Criteria andReceptionDateIsNull() {
            addCriterion("reception_date is null");
            return (Criteria) this;
        }

        public Criteria andReceptionDateIsNotNull() {
            addCriterion("reception_date is not null");
            return (Criteria) this;
        }

        public Criteria andReceptionDateEqualTo(String value) {
            addCriterion("reception_date =", value, "receptionDate");
            return (Criteria) this;
        }

        public Criteria andReceptionDateNotEqualTo(String value) {
            addCriterion("reception_date <>", value, "receptionDate");
            return (Criteria) this;
        }

        public Criteria andReceptionDateGreaterThan(String value) {
            addCriterion("reception_date >", value, "receptionDate");
            return (Criteria) this;
        }

        public Criteria andReceptionDateGreaterThanOrEqualTo(String value) {
            addCriterion("reception_date >=", value, "receptionDate");
            return (Criteria) this;
        }

        public Criteria andReceptionDateLessThan(String value) {
            addCriterion("reception_date <", value, "receptionDate");
            return (Criteria) this;
        }

        public Criteria andReceptionDateLessThanOrEqualTo(String value) {
            addCriterion("reception_date <=", value, "receptionDate");
            return (Criteria) this;
        }

        public Criteria andReceptionDateLike(String value) {
            addCriterion("reception_date like", value, "receptionDate");
            return (Criteria) this;
        }

        public Criteria andReceptionDateNotLike(String value) {
            addCriterion("reception_date not like", value, "receptionDate");
            return (Criteria) this;
        }

        public Criteria andReceptionDateIn(List<String> values) {
            addCriterion("reception_date in", values, "receptionDate");
            return (Criteria) this;
        }

        public Criteria andReceptionDateNotIn(List<String> values) {
            addCriterion("reception_date not in", values, "receptionDate");
            return (Criteria) this;
        }

        public Criteria andReceptionDateBetween(String value1, String value2) {
            addCriterion("reception_date between", value1, value2, "receptionDate");
            return (Criteria) this;
        }

        public Criteria andReceptionDateNotBetween(String value1, String value2) {
            addCriterion("reception_date not between", value1, value2, "receptionDate");
            return (Criteria) this;
        }

        public Criteria andInterestRateIsNull() {
            addCriterion("interest_rate is null");
            return (Criteria) this;
        }

        public Criteria andInterestRateIsNotNull() {
            addCriterion("interest_rate is not null");
            return (Criteria) this;
        }

        public Criteria andInterestRateEqualTo(BigDecimal value) {
            addCriterion("interest_rate =", value, "interestRate");
            return (Criteria) this;
        }

        public Criteria andInterestRateNotEqualTo(BigDecimal value) {
            addCriterion("interest_rate <>", value, "interestRate");
            return (Criteria) this;
        }

        public Criteria andInterestRateGreaterThan(BigDecimal value) {
            addCriterion("interest_rate >", value, "interestRate");
            return (Criteria) this;
        }

        public Criteria andInterestRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("interest_rate >=", value, "interestRate");
            return (Criteria) this;
        }

        public Criteria andInterestRateLessThan(BigDecimal value) {
            addCriterion("interest_rate <", value, "interestRate");
            return (Criteria) this;
        }

        public Criteria andInterestRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("interest_rate <=", value, "interestRate");
            return (Criteria) this;
        }

        public Criteria andInterestRateIn(List<BigDecimal> values) {
            addCriterion("interest_rate in", values, "interestRate");
            return (Criteria) this;
        }

        public Criteria andInterestRateNotIn(List<BigDecimal> values) {
            addCriterion("interest_rate not in", values, "interestRate");
            return (Criteria) this;
        }

        public Criteria andInterestRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("interest_rate between", value1, value2, "interestRate");
            return (Criteria) this;
        }

        public Criteria andInterestRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("interest_rate not between", value1, value2, "interestRate");
            return (Criteria) this;
        }

        public Criteria andCostRateIsNull() {
            addCriterion("cost_rate is null");
            return (Criteria) this;
        }

        public Criteria andCostRateIsNotNull() {
            addCriterion("cost_rate is not null");
            return (Criteria) this;
        }

        public Criteria andCostRateEqualTo(BigDecimal value) {
            addCriterion("cost_rate =", value, "costRate");
            return (Criteria) this;
        }

        public Criteria andCostRateNotEqualTo(BigDecimal value) {
            addCriterion("cost_rate <>", value, "costRate");
            return (Criteria) this;
        }

        public Criteria andCostRateGreaterThan(BigDecimal value) {
            addCriterion("cost_rate >", value, "costRate");
            return (Criteria) this;
        }

        public Criteria andCostRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cost_rate >=", value, "costRate");
            return (Criteria) this;
        }

        public Criteria andCostRateLessThan(BigDecimal value) {
            addCriterion("cost_rate <", value, "costRate");
            return (Criteria) this;
        }

        public Criteria andCostRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cost_rate <=", value, "costRate");
            return (Criteria) this;
        }

        public Criteria andCostRateIn(List<BigDecimal> values) {
            addCriterion("cost_rate in", values, "costRate");
            return (Criteria) this;
        }

        public Criteria andCostRateNotIn(List<BigDecimal> values) {
            addCriterion("cost_rate not in", values, "costRate");
            return (Criteria) this;
        }

        public Criteria andCostRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cost_rate between", value1, value2, "costRate");
            return (Criteria) this;
        }

        public Criteria andCostRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cost_rate not between", value1, value2, "costRate");
            return (Criteria) this;
        }

        public Criteria andInterestRateStandardIsNull() {
            addCriterion("interest_rate_standard is null");
            return (Criteria) this;
        }

        public Criteria andInterestRateStandardIsNotNull() {
            addCriterion("interest_rate_standard is not null");
            return (Criteria) this;
        }

        public Criteria andInterestRateStandardEqualTo(String value) {
            addCriterion("interest_rate_standard =", value, "interestRateStandard");
            return (Criteria) this;
        }

        public Criteria andInterestRateStandardNotEqualTo(String value) {
            addCriterion("interest_rate_standard <>", value, "interestRateStandard");
            return (Criteria) this;
        }

        public Criteria andInterestRateStandardGreaterThan(String value) {
            addCriterion("interest_rate_standard >", value, "interestRateStandard");
            return (Criteria) this;
        }

        public Criteria andInterestRateStandardGreaterThanOrEqualTo(String value) {
            addCriterion("interest_rate_standard >=", value, "interestRateStandard");
            return (Criteria) this;
        }

        public Criteria andInterestRateStandardLessThan(String value) {
            addCriterion("interest_rate_standard <", value, "interestRateStandard");
            return (Criteria) this;
        }

        public Criteria andInterestRateStandardLessThanOrEqualTo(String value) {
            addCriterion("interest_rate_standard <=", value, "interestRateStandard");
            return (Criteria) this;
        }

        public Criteria andInterestRateStandardLike(String value) {
            addCriterion("interest_rate_standard like", value, "interestRateStandard");
            return (Criteria) this;
        }

        public Criteria andInterestRateStandardNotLike(String value) {
            addCriterion("interest_rate_standard not like", value, "interestRateStandard");
            return (Criteria) this;
        }

        public Criteria andInterestRateStandardIn(List<String> values) {
            addCriterion("interest_rate_standard in", values, "interestRateStandard");
            return (Criteria) this;
        }

        public Criteria andInterestRateStandardNotIn(List<String> values) {
            addCriterion("interest_rate_standard not in", values, "interestRateStandard");
            return (Criteria) this;
        }

        public Criteria andInterestRateStandardBetween(String value1, String value2) {
            addCriterion("interest_rate_standard between", value1, value2, "interestRateStandard");
            return (Criteria) this;
        }

        public Criteria andInterestRateStandardNotBetween(String value1, String value2) {
            addCriterion("interest_rate_standard not between", value1, value2, "interestRateStandard");
            return (Criteria) this;
        }

        public Criteria andDykInterestRateIsNull() {
            addCriterion("dyk_interest_rate is null");
            return (Criteria) this;
        }

        public Criteria andDykInterestRateIsNotNull() {
            addCriterion("dyk_interest_rate is not null");
            return (Criteria) this;
        }

        public Criteria andDykInterestRateEqualTo(BigDecimal value) {
            addCriterion("dyk_interest_rate =", value, "dykInterestRate");
            return (Criteria) this;
        }

        public Criteria andDykInterestRateNotEqualTo(BigDecimal value) {
            addCriterion("dyk_interest_rate <>", value, "dykInterestRate");
            return (Criteria) this;
        }

        public Criteria andDykInterestRateGreaterThan(BigDecimal value) {
            addCriterion("dyk_interest_rate >", value, "dykInterestRate");
            return (Criteria) this;
        }

        public Criteria andDykInterestRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("dyk_interest_rate >=", value, "dykInterestRate");
            return (Criteria) this;
        }

        public Criteria andDykInterestRateLessThan(BigDecimal value) {
            addCriterion("dyk_interest_rate <", value, "dykInterestRate");
            return (Criteria) this;
        }

        public Criteria andDykInterestRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("dyk_interest_rate <=", value, "dykInterestRate");
            return (Criteria) this;
        }

        public Criteria andDykInterestRateIn(List<BigDecimal> values) {
            addCriterion("dyk_interest_rate in", values, "dykInterestRate");
            return (Criteria) this;
        }

        public Criteria andDykInterestRateNotIn(List<BigDecimal> values) {
            addCriterion("dyk_interest_rate not in", values, "dykInterestRate");
            return (Criteria) this;
        }

        public Criteria andDykInterestRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("dyk_interest_rate between", value1, value2, "dykInterestRate");
            return (Criteria) this;
        }

        public Criteria andDykInterestRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("dyk_interest_rate not between", value1, value2, "dykInterestRate");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table interest_management
     *
     * @mbggenerated do_not_delete_during_merge Tue May 23 10:15:46 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}