package com.ut.scf.pojo.auto;

import java.math.BigDecimal;
import java.util.Date;

public class LoanInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.loan_id
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    private String loanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.loan_date
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    private Date loanDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.contract_no
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    private String contractNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.order_batch_id
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    private String orderBatchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.order_accept_money
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    private BigDecimal orderAcceptMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.order_all_money
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    private BigDecimal orderAllMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.loan_amt
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    private BigDecimal loanAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.finance_start_day
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    private Date financeStartDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.finance_due_day
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    private Date financeDueDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.guarantee_money_rate
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    private BigDecimal guaranteeMoneyRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.guarantee_money
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    private BigDecimal guaranteeMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.guarantee_money_actual
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    private BigDecimal guaranteeMoneyActual;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.loan_id
     *
     * @return the value of loan_info.loan_id
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    public String getLoanId() {
        return loanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.loan_id
     *
     * @param loanId the value for loan_info.loan_id
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    public void setLoanId(String loanId) {
        this.loanId = loanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.loan_date
     *
     * @return the value of loan_info.loan_date
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    public Date getLoanDate() {
        return loanDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.loan_date
     *
     * @param loanDate the value for loan_info.loan_date
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    public void setLoanDate(Date loanDate) {
        this.loanDate = loanDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.contract_no
     *
     * @return the value of loan_info.contract_no
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    public String getContractNo() {
        return contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.contract_no
     *
     * @param contractNo the value for loan_info.contract_no
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    public void setContractNo(String contractNo) {
        this.contractNo = contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.order_batch_id
     *
     * @return the value of loan_info.order_batch_id
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    public String getOrderBatchId() {
        return orderBatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.order_batch_id
     *
     * @param orderBatchId the value for loan_info.order_batch_id
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    public void setOrderBatchId(String orderBatchId) {
        this.orderBatchId = orderBatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.order_accept_money
     *
     * @return the value of loan_info.order_accept_money
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    public BigDecimal getOrderAcceptMoney() {
        return orderAcceptMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.order_accept_money
     *
     * @param orderAcceptMoney the value for loan_info.order_accept_money
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    public void setOrderAcceptMoney(BigDecimal orderAcceptMoney) {
        this.orderAcceptMoney = orderAcceptMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.order_all_money
     *
     * @return the value of loan_info.order_all_money
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    public BigDecimal getOrderAllMoney() {
        return orderAllMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.order_all_money
     *
     * @param orderAllMoney the value for loan_info.order_all_money
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    public void setOrderAllMoney(BigDecimal orderAllMoney) {
        this.orderAllMoney = orderAllMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.loan_amt
     *
     * @return the value of loan_info.loan_amt
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    public BigDecimal getLoanAmt() {
        return loanAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.loan_amt
     *
     * @param loanAmt the value for loan_info.loan_amt
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    public void setLoanAmt(BigDecimal loanAmt) {
        this.loanAmt = loanAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.finance_start_day
     *
     * @return the value of loan_info.finance_start_day
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    public Date getFinanceStartDay() {
        return financeStartDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.finance_start_day
     *
     * @param financeStartDay the value for loan_info.finance_start_day
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    public void setFinanceStartDay(Date financeStartDay) {
        this.financeStartDay = financeStartDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.finance_due_day
     *
     * @return the value of loan_info.finance_due_day
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    public Date getFinanceDueDay() {
        return financeDueDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.finance_due_day
     *
     * @param financeDueDay the value for loan_info.finance_due_day
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    public void setFinanceDueDay(Date financeDueDay) {
        this.financeDueDay = financeDueDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.guarantee_money_rate
     *
     * @return the value of loan_info.guarantee_money_rate
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    public BigDecimal getGuaranteeMoneyRate() {
        return guaranteeMoneyRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.guarantee_money_rate
     *
     * @param guaranteeMoneyRate the value for loan_info.guarantee_money_rate
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    public void setGuaranteeMoneyRate(BigDecimal guaranteeMoneyRate) {
        this.guaranteeMoneyRate = guaranteeMoneyRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.guarantee_money
     *
     * @return the value of loan_info.guarantee_money
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    public BigDecimal getGuaranteeMoney() {
        return guaranteeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.guarantee_money
     *
     * @param guaranteeMoney the value for loan_info.guarantee_money
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    public void setGuaranteeMoney(BigDecimal guaranteeMoney) {
        this.guaranteeMoney = guaranteeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.guarantee_money_actual
     *
     * @return the value of loan_info.guarantee_money_actual
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    public BigDecimal getGuaranteeMoneyActual() {
        return guaranteeMoneyActual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.guarantee_money_actual
     *
     * @param guaranteeMoneyActual the value for loan_info.guarantee_money_actual
     *
     * @mbggenerated Wed May 24 10:52:41 CST 2017
     */
    public void setGuaranteeMoneyActual(BigDecimal guaranteeMoneyActual) {
        this.guaranteeMoneyActual = guaranteeMoneyActual;
    }
}