package com.ut.scf.dao.auto;

import com.ut.scf.pojo.auto.FinanceInfo;
import com.ut.scf.pojo.auto.FinanceInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FinanceInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table finance_info
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	int countByExample(FinanceInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table finance_info
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	int deleteByExample(FinanceInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table finance_info
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	int deleteByPrimaryKey(String financeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table finance_info
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	int insert(FinanceInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table finance_info
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	int insertSelective(FinanceInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table finance_info
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	List<FinanceInfo> selectByExample(FinanceInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table finance_info
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	FinanceInfo selectByPrimaryKey(String financeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table finance_info
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	int updateByExampleSelective(@Param("record") FinanceInfo record,
			@Param("example") FinanceInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table finance_info
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	int updateByExample(@Param("record") FinanceInfo record,
			@Param("example") FinanceInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table finance_info
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	int updateByPrimaryKeySelective(FinanceInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table finance_info
	 * @mbggenerated  Thu Jun 08 18:30:16 CST 2017
	 */
	int updateByPrimaryKey(FinanceInfo record);
}