package com.ut.scf.dao.auto;

import com.ut.scf.pojo.auto.GuaranteeMoneyManagement;
import com.ut.scf.pojo.auto.GuaranteeMoneyManagementExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GuaranteeMoneyManagementMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guarantee_money_management
	 * @mbggenerated  Mon May 22 16:49:27 CST 2017
	 */
	int countByExample(GuaranteeMoneyManagementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guarantee_money_management
	 * @mbggenerated  Mon May 22 16:49:27 CST 2017
	 */
	int deleteByExample(GuaranteeMoneyManagementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guarantee_money_management
	 * @mbggenerated  Mon May 22 16:49:27 CST 2017
	 */
	int deleteByPrimaryKey(String productId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guarantee_money_management
	 * @mbggenerated  Mon May 22 16:49:27 CST 2017
	 */
	int insert(GuaranteeMoneyManagement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guarantee_money_management
	 * @mbggenerated  Mon May 22 16:49:27 CST 2017
	 */
	int insertSelective(GuaranteeMoneyManagement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guarantee_money_management
	 * @mbggenerated  Mon May 22 16:49:27 CST 2017
	 */
	List<GuaranteeMoneyManagement> selectByExample(
			GuaranteeMoneyManagementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guarantee_money_management
	 * @mbggenerated  Mon May 22 16:49:27 CST 2017
	 */
	GuaranteeMoneyManagement selectByPrimaryKey(String productId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guarantee_money_management
	 * @mbggenerated  Mon May 22 16:49:27 CST 2017
	 */
	int updateByExampleSelective(
			@Param("record") GuaranteeMoneyManagement record,
			@Param("example") GuaranteeMoneyManagementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guarantee_money_management
	 * @mbggenerated  Mon May 22 16:49:27 CST 2017
	 */
	int updateByExample(@Param("record") GuaranteeMoneyManagement record,
			@Param("example") GuaranteeMoneyManagementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guarantee_money_management
	 * @mbggenerated  Mon May 22 16:49:27 CST 2017
	 */
	int updateByPrimaryKeySelective(GuaranteeMoneyManagement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guarantee_money_management
	 * @mbggenerated  Mon May 22 16:49:27 CST 2017
	 */
	int updateByPrimaryKey(GuaranteeMoneyManagement record);
}