package com.ut.scf.dao.auto;

import com.ut.scf.pojo.auto.SysUserRole;
import com.ut.scf.pojo.auto.SysUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysUserRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbggenerated  Thu May 18 13:27:13 CST 2017
	 */
	int countByExample(SysUserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbggenerated  Thu May 18 13:27:13 CST 2017
	 */
	int deleteByExample(SysUserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbggenerated  Thu May 18 13:27:13 CST 2017
	 */
	int deleteByPrimaryKey(String recUid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbggenerated  Thu May 18 13:27:13 CST 2017
	 */
	int insert(SysUserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbggenerated  Thu May 18 13:27:13 CST 2017
	 */
	int insertSelective(SysUserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbggenerated  Thu May 18 13:27:13 CST 2017
	 */
	List<SysUserRole> selectByExample(SysUserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbggenerated  Thu May 18 13:27:13 CST 2017
	 */
	SysUserRole selectByPrimaryKey(String recUid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbggenerated  Thu May 18 13:27:13 CST 2017
	 */
	int updateByExampleSelective(@Param("record") SysUserRole record,
			@Param("example") SysUserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbggenerated  Thu May 18 13:27:13 CST 2017
	 */
	int updateByExample(@Param("record") SysUserRole record,
			@Param("example") SysUserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbggenerated  Thu May 18 13:27:13 CST 2017
	 */
	int updateByPrimaryKeySelective(SysUserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbggenerated  Thu May 18 13:27:13 CST 2017
	 */
	int updateByPrimaryKey(SysUserRole record);
}