package com.ut.scf.dao.auto;

import com.ut.scf.pojo.auto.InterestManagement;
import com.ut.scf.pojo.auto.InterestManagementExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InterestManagementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    int countByExample(InterestManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    int deleteByExample(InterestManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    int deleteByPrimaryKey(String recUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    int insert(InterestManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    int insertSelective(InterestManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    List<InterestManagement> selectByExample(InterestManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    InterestManagement selectByPrimaryKey(String recUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    int updateByExampleSelective(@Param("record") InterestManagement record, @Param("example") InterestManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    int updateByExample(@Param("record") InterestManagement record, @Param("example") InterestManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    int updateByPrimaryKeySelective(InterestManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_management
     *
     * @mbggenerated Tue May 23 10:15:46 CST 2017
     */
    int updateByPrimaryKey(InterestManagement record);
}