package com.ut.scf.pojo.auto;

import java.math.BigDecimal;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class RepaymentPlanInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column repayment_plan_info.order_id
	 * 
	 * @mbggenerated Mon Jun 12 14:35:33 CST 2017
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column repayment_plan_info.period
	 * 
	 * @mbggenerated Mon Jun 12 14:35:33 CST 2017
	 */
	private Byte period;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column repayment_plan_info.current_repay_date
	 * 
	 * @mbggenerated Mon Jun 12 14:35:33 CST 2017
	 */
	@JsonFormat(pattern = "yyyy-MM-dd")
	private Date currentRepayDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column repayment_plan_info.current_payable_principal
	 * 
	 * @mbggenerated Mon Jun 12 14:35:33 CST 2017
	 */
	private BigDecimal currentPayablePrincipal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column repayment_plan_info.current_payable_interest
	 * 
	 * @mbggenerated Mon Jun 12 14:35:33 CST 2017
	 */
	private BigDecimal currentPayableInterest;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column repayment_plan_info.student_repay_status
	 * 
	 * @mbggenerated Mon Jun 12 14:35:33 CST 2017
	 */
	private String studentRepayStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column repayment_plan_info.super_repay_status
	 * 
	 * @mbggenerated Mon Jun 12 14:35:33 CST 2017
	 */
	private String superRepayStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column repayment_plan_info.order_batch_id
	 * 
	 * @mbggenerated Mon Jun 12 14:35:33 CST 2017
	 */
	private String orderBatchId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column repayment_plan_info.order_id
	 * 
	 * @return the value of repayment_plan_info.order_id
	 * @mbggenerated Mon Jun 12 14:35:33 CST 2017
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column repayment_plan_info.order_id
	 * 
	 * @param orderId
	 *            the value for repayment_plan_info.order_id
	 * @mbggenerated Mon Jun 12 14:35:33 CST 2017
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column repayment_plan_info.period
	 * 
	 * @return the value of repayment_plan_info.period
	 * @mbggenerated Mon Jun 12 14:35:33 CST 2017
	 */
	public Byte getPeriod() {
		return period;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column repayment_plan_info.period
	 * 
	 * @param period
	 *            the value for repayment_plan_info.period
	 * @mbggenerated Mon Jun 12 14:35:33 CST 2017
	 */
	public void setPeriod(Byte period) {
		this.period = period;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column repayment_plan_info.current_repay_date
	 * 
	 * @return the value of repayment_plan_info.current_repay_date
	 * @mbggenerated Mon Jun 12 14:35:33 CST 2017
	 */
	public Date getCurrentRepayDate() {
		return currentRepayDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column repayment_plan_info.current_repay_date
	 * 
	 * @param currentRepayDate
	 *            the value for repayment_plan_info.current_repay_date
	 * @mbggenerated Mon Jun 12 14:35:33 CST 2017
	 */
	public void setCurrentRepayDate(Date currentRepayDate) {
		this.currentRepayDate = currentRepayDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column
	 * repayment_plan_info.current_payable_principal
	 * 
	 * @return the value of repayment_plan_info.current_payable_principal
	 * @mbggenerated Mon Jun 12 14:35:33 CST 2017
	 */
	public BigDecimal getCurrentPayablePrincipal() {
		return currentPayablePrincipal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column
	 * repayment_plan_info.current_payable_principal
	 * 
	 * @param currentPayablePrincipal
	 *            the value for repayment_plan_info.current_payable_principal
	 * @mbggenerated Mon Jun 12 14:35:33 CST 2017
	 */
	public void setCurrentPayablePrincipal(BigDecimal currentPayablePrincipal) {
		this.currentPayablePrincipal = currentPayablePrincipal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column repayment_plan_info.current_payable_interest
	 * 
	 * @return the value of repayment_plan_info.current_payable_interest
	 * @mbggenerated Mon Jun 12 14:35:33 CST 2017
	 */
	public BigDecimal getCurrentPayableInterest() {
		return currentPayableInterest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column repayment_plan_info.current_payable_interest
	 * 
	 * @param currentPayableInterest
	 *            the value for repayment_plan_info.current_payable_interest
	 * @mbggenerated Mon Jun 12 14:35:33 CST 2017
	 */
	public void setCurrentPayableInterest(BigDecimal currentPayableInterest) {
		this.currentPayableInterest = currentPayableInterest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column repayment_plan_info.student_repay_status
	 * 
	 * @return the value of repayment_plan_info.student_repay_status
	 * @mbggenerated Mon Jun 12 14:35:33 CST 2017
	 */
	public String getStudentRepayStatus() {
		return studentRepayStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column repayment_plan_info.student_repay_status
	 * 
	 * @param studentRepayStatus
	 *            the value for repayment_plan_info.student_repay_status
	 * @mbggenerated Mon Jun 12 14:35:33 CST 2017
	 */
	public void setStudentRepayStatus(String studentRepayStatus) {
		this.studentRepayStatus = studentRepayStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column repayment_plan_info.super_repay_status
	 * 
	 * @return the value of repayment_plan_info.super_repay_status
	 * @mbggenerated Mon Jun 12 14:35:33 CST 2017
	 */
	public String getSuperRepayStatus() {
		return superRepayStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column repayment_plan_info.super_repay_status
	 * 
	 * @param superRepayStatus
	 *            the value for repayment_plan_info.super_repay_status
	 * @mbggenerated Mon Jun 12 14:35:33 CST 2017
	 */
	public void setSuperRepayStatus(String superRepayStatus) {
		this.superRepayStatus = superRepayStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column repayment_plan_info.order_batch_id
	 * 
	 * @return the value of repayment_plan_info.order_batch_id
	 * @mbggenerated Mon Jun 12 14:35:33 CST 2017
	 */
	public String getOrderBatchId() {
		return orderBatchId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column repayment_plan_info.order_batch_id
	 * 
	 * @param orderBatchId
	 *            the value for repayment_plan_info.order_batch_id
	 * @mbggenerated Mon Jun 12 14:35:33 CST 2017
	 */
	public void setOrderBatchId(String orderBatchId) {
		this.orderBatchId = orderBatchId;
	}
}